import type {GameState} from '../hooks/useGameLoop';
import {bistroOffers,servicePlan,RestaurantServicePlan,isPastry,walkInCapacity} from '../restaurantOperations';
import {restaurantLevel} from '../restaurantProgression';
import {serviceProfile} from '../restaurantPersonality';

export function RestaurantServiceControls({state,onChange,onBook,onCancel}:{state:GameState;onChange:(changes:Partial<RestaurantServicePlan>)=>void;onBook:(id:string)=>void;onCancel:(id:string)=>void}){
 if(!state.restaurantType)return null;
 const plan=servicePlan(state),level=restaurantLevel(state),profile=serviceProfile(state),cafe=state.restaurantType==='cafe',bistro=state.restaurantType==='bistro';
 return <section className="mc-inner-panel restaurant-progress" aria-label="Restaurant service style">
  <h3>{bistro?'Reservations & dining pace':cafe?'Coffee bar & bakery':'Dining room & pickup counter'}</h3>
  <p>{profile.description}</p>
  <p><strong>Kitchen workload:</strong> {state.orders.filter(o=>o.state!=='ready').length} dishes preparing · {state.orders.filter(o=>o.state==='ready').length} ready to collect</p>
  {!bistro&&<><label className="flex gap-3 items-center"><input type="checkbox" checked={plan.pickup} disabled={level<2} onChange={e=>onChange({pickup:e.target.checked})}/>Accept takeaway pickup orders {level<2?'· opens at Level 2':''}</label><p>Guests collect at the counter without taking a table. No app commission; each order uses real ingredients and shares your cooks. Up to three pickup guests at once.</p></>}
  {cafe&&<div className="space-y-3"><label className="flex gap-3 items-center"><input type="checkbox" checked={plan.coffeeFirst} onChange={e=>onChange({coffeeFirst:e.target.checked})}/>Barista: prepare coffee orders first</label><label>Bakery batch size<select className="mc-button ml-3 p-2" aria-label="Bakery batch size" disabled={level<3} value={plan.pastryBatch} onChange={e=>onChange({pastryBatch:Number(e.target.value) as 1|2|4})}><option value={1}>One pastry at a time</option><option value={2}>Two together · 20% less preparation per pastry</option><option value={4}>Four together · 35% less preparation per pastry</option></select></label><p>{level<3?'Bakery batching opens at Level 3. ':''}The baker groups ordered pastries of the same recipe. Ingredients are consumed for every portion; no unwanted batches are made. Serve baked items promptly: waiting over 10 service seconds reduces tips.</p><p>{state.orders.filter(o=>isPastry(o.recipeId)&&o.state!=='ready').length} pastries in the bakery queue. Coffee priority shares staff with baking; manual table priority takes precedence.</p></div>}
  {bistro&&<><div className="grid md:grid-cols-2 gap-3"><label>Dining pace<select className="mc-button block w-full p-2" aria-label="Dining pace" value={plan.pace} onChange={e=>onChange({pace:e.target.value as RestaurantServicePlan['pace']})}><option value="relaxed">Relaxed · fill half the dining room</option><option value="balanced">Balanced · fill three quarters</option><option value="busy">Busy · use every table</option></select></label><label>Seasonal special<select className="mc-button block w-full p-2" aria-label="Seasonal special" value={state.activeMenu.includes(plan.specialId)?plan.specialId:''} onChange={e=>onChange({specialId:e.target.value})}><option value="">No featured dish</option>{state.recipes.filter(r=>r.unlocked&&state.activeMenu.includes(r.id)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><p>Up to {walkInCapacity(state)} tables filled by walk-ins. A featured dish is 60% more likely to be chosen at the same price; check its stock. Accepted bookings take priority over walk-ins.</p><h3>Evening reservation requests</h3><p>{level<2?'Opens at Level 2.':'Choose which requests to accept. A table is held shortly before 18:00; dirty or occupied tables can cause a missed booking. Guests pay after their meal. Cancel before arrival at no cost.'}</p><div className="grid md:grid-cols-2 gap-3">{bistroOffers(state).map(offer=>{const booking=state.bookings?.find(b=>b.id===offer.id);return <article className="mc-slot p-3" key={offer.id}><strong>{offer.name}</strong><p>Day {offer.day} · 18:00 · {offer.party} guests</p>{booking?<><p role="status">{booking.status==='accepted'?`Confirmed · Table ${state.tables.findIndex(t=>t.id===booking.tableId)+1}`:booking.status}</p>{booking.status==='accepted'&&state.time<offer.time&&<button className="mc-button" onClick={()=>onCancel(offer.id)}>Cancel {offer.name}</button>}</>:<button className="mc-button-green" disabled={state.time>=offer.time||state.phase==='closing'} onClick={()=>onBook(offer.id)}>Accept {offer.name}</button>}</article>;})}</div></>}
 </section>;
}
