/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/a_slim_female_character.glb -o src/components/SlimFemale.tsx -r public 
Author: YØD (https://sketchfab.com/YOD3DD)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-slim-female-character-7d1a063e5f01475e9cdaf85bc53beb24
Title: A slim, female character
*/

import * as THREE from 'three'
import React, { useRef, useMemo } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshBasicMaterial
  }
}

export function SlimFemale({ isWalking = false, isSitting = false, color, ...props }: { isWalking?: boolean, isSitting?: boolean, color?: string } & React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/a_slim_female_character.glb') as unknown as GLTFResult
  const group = useRef<THREE.Group>(null)

  // Use a cloned material so we can colorize it later if needed, 
  const mat = useMemo(() => {
    const m = materials.material_0.clone();
    if (color) {
      // Just multiply the base color to keep texture but add tint
      m.color.set(color);
    }
    return m;
  }, [materials, color]);

  useFrame((state) => {
    if (!group.current) return;
    
    const t = state.clock.elapsedTime * 10;
    
    let targetY = 0;
    let targetRotZ = 0;
    let targetRotX = 0;

    if (isSitting) {
      targetY = -0.5; // Sink into the chair
      targetRotX = 0;
    } else if (isWalking) {
      targetY = Math.abs(Math.sin(t * 1.5)) * 0.15; // EXAGGERATED HOP
      targetRotZ = Math.sin(t * 0.75) * 0.2; // Sway
      targetRotX = Math.sin(t * 1.5) * 0.1; // Forward lean
    }

    group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, targetY, 0.2);
    group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, targetRotZ, 0.2);
    group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, targetRotX, 0.2);
  })

  return (
    <group ref={group} {...props} dispose={null}>
      {/* 
        This character's scale and rotation may need tweaking.
        We apply scale 1 to see how big it is by default, then we can adjust.
      */}
      <mesh 
        geometry={nodes.Object_4.geometry} 
        material={mat} 
        rotation={[-Math.PI / 2, 0, 0]} // typical GLTF rotation fix
        scale={[0.015, 0.015, 0.015]} // start with a small scale guess, similar to the last one
        castShadow 
        receiveShadow 
      />
    </group>
  )
}

useGLTF.preload('/a_slim_female_character.glb')
