// Generated from the exported asset manifest.
export const castCatalog=[
 {
  "id": "amira",
  "name": "Amira",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 22,
  "heightMetres": 1.62,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "noah",
  "name": "Noah",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 31,
  "heightMetres": 1.82,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "sofia",
  "name": "Sofia",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 38,
  "heightMetres": 1.6,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "daniel",
  "name": "Daniel",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 47,
  "heightMetres": 1.84,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "mei",
  "name": "Mei",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 27,
  "heightMetres": 1.75,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "marcus",
  "name": "Marcus",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 54,
  "heightMetres": 1.83,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "elena",
  "name": "Elena",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 64,
  "heightMetres": 1.71,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ravi",
  "name": "Ravi",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 35,
  "heightMetres": 1.73,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "rose",
  "name": "Rose",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 73,
  "heightMetres": 1.61,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "tom",
  "name": "Tom",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 68,
  "heightMetres": 1.88,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "nina",
  "name": "Nina",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 24,
  "heightMetres": 1.72,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "leo",
  "name": "Leo",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 29,
  "heightMetres": 1.79,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "iris",
  "name": "Iris",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 43,
  "heightMetres": 1.61,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "omar",
  "name": "Omar",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 57,
  "heightMetres": 1.79,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "grace",
  "name": "Grace",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 70,
  "heightMetres": 1.65,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "aisha",
  "name": "Aisha",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 22,
  "heightMetres": 1.78,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ethan",
  "name": "Ethan",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 31,
  "heightMetres": 1.78,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "leila",
  "name": "Leila",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 38,
  "heightMetres": 1.64,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "victor",
  "name": "Victor",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 47,
  "heightMetres": 1.85,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "chloe",
  "name": "Chloe",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 27,
  "heightMetres": 1.74,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "samir",
  "name": "Samir",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 54,
  "heightMetres": 1.78,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "lucia",
  "name": "Lucia",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 64,
  "heightMetres": 1.73,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "henry",
  "name": "Henry",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 35,
  "heightMetres": 1.79,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "yuna",
  "name": "Yuna",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 73,
  "heightMetres": 1.61,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "isaac",
  "name": "Isaac",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 68,
  "heightMetres": 1.79,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "freya",
  "name": "Freya",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 24,
  "heightMetres": 1.66,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "dev",
  "name": "Dev",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 29,
  "heightMetres": 1.82,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "zara",
  "name": "Zara",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 43,
  "heightMetres": 1.63,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "felix",
  "name": "Felix",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 57,
  "heightMetres": 1.75,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "amal",
  "name": "Amal",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 70,
  "heightMetres": 1.72,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "oscar",
  "name": "Oscar",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 22,
  "heightMetres": 1.72,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "julia",
  "name": "Julia",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 31,
  "heightMetres": 1.73,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "kenji",
  "name": "Kenji",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 38,
  "heightMetres": 1.79,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ada",
  "name": "Ada",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 47,
  "heightMetres": 1.67,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "leon",
  "name": "Leon",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 27,
  "heightMetres": 1.87,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "helen",
  "name": "Helen",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 54,
  "heightMetres": 1.63,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "peter",
  "name": "Peter",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 64,
  "heightMetres": 1.77,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "farah",
  "name": "Farah",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 35,
  "heightMetres": 1.68,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "andre",
  "name": "Andre",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 73,
  "heightMetres": 1.88,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "lina",
  "name": "Lina",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 68,
  "heightMetres": 1.65,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "hugo",
  "name": "Hugo",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 24,
  "heightMetres": 1.74,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "maria",
  "name": "Maria",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 29,
  "heightMetres": 1.64,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "yusuf",
  "name": "Yusuf",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 43,
  "heightMetres": 1.72,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "olivia",
  "name": "Olivia",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 57,
  "heightMetres": 1.68,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "nathan",
  "name": "Nathan",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 70,
  "heightMetres": 1.84,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "bea",
  "name": "Bea",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 22,
  "heightMetres": 1.7,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "arjun",
  "name": "Arjun",
  "group": "customers",
  "role": "customer",
  "detail": "Jacket & full-length jeans",
  "ageYears": 31,
  "heightMetres": 1.86,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "sara",
  "name": "Sara",
  "group": "customers",
  "role": "customer",
  "detail": "Suit & full-length trousers",
  "ageYears": 38,
  "heightMetres": 1.67,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "george",
  "name": "George",
  "group": "customers",
  "role": "customer",
  "detail": "Long-sleeved shirt & trousers",
  "ageYears": 47,
  "heightMetres": 1.82,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "layla",
  "name": "Layla",
  "group": "customers",
  "role": "customer",
  "detail": "Striped shirt & trousers",
  "ageYears": 27,
  "heightMetres": 1.62,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "theo",
  "name": "Theo",
  "group": "staff",
  "role": "waiter",
  "detail": "Table service \u00b7 Suit & full-length trousers",
  "ageYears": 23,
  "heightMetres": 1.85,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "maya",
  "name": "Maya",
  "group": "staff",
  "role": "chef",
  "detail": "Kitchen team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 30,
  "heightMetres": 1.78,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "lucas",
  "name": "Lucas",
  "group": "staff",
  "role": "maintenance",
  "detail": "Maintenance \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 37,
  "heightMetres": 1.85,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "hana",
  "name": "Hana",
  "group": "staff",
  "role": "cleaner",
  "detail": "Cleaning team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 44,
  "heightMetres": 1.74,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ben",
  "name": "Ben",
  "group": "staff",
  "role": "helper",
  "detail": "Supplies team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 51,
  "heightMetres": 1.86,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "eva",
  "name": "Eva",
  "group": "staff",
  "role": "waiter",
  "detail": "Table service \u00b7 Suit & full-length trousers",
  "ageYears": 23,
  "heightMetres": 1.6,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "adam",
  "name": "Adam",
  "group": "staff",
  "role": "waiter",
  "detail": "Table service \u00b7 Suit & full-length trousers",
  "ageYears": 30,
  "heightMetres": 1.79,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "fatima",
  "name": "Fatima",
  "group": "staff",
  "role": "chef",
  "detail": "Kitchen team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 37,
  "heightMetres": 1.68,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "louis",
  "name": "Louis",
  "group": "staff",
  "role": "chef",
  "detail": "Kitchen team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 44,
  "heightMetres": 1.85,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "alice",
  "name": "Alice",
  "group": "staff",
  "role": "cleaner",
  "detail": "Cleaning team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 51,
  "heightMetres": 1.63,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "idris",
  "name": "Idris",
  "group": "staff",
  "role": "cleaner",
  "detail": "Cleaning team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 23,
  "heightMetres": 1.82,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "milan",
  "name": "Milan",
  "group": "staff",
  "role": "helper",
  "detail": "Supplies team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 30,
  "heightMetres": 1.87,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "anika",
  "name": "Anika",
  "group": "staff",
  "role": "helper",
  "detail": "Supplies team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 37,
  "heightMetres": 1.6,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "jack",
  "name": "Jack",
  "group": "staff",
  "role": "maintenance",
  "detail": "Maintenance \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 44,
  "heightMetres": 1.86,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "clara",
  "name": "Clara",
  "group": "staff",
  "role": "receptionist",
  "detail": "Reception \u00b7 Suit & full-length trousers",
  "ageYears": 51,
  "heightMetres": 1.71,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "alex",
  "name": "Alex",
  "group": "staff",
  "role": "receptionist",
  "detail": "Reception \u00b7 Suit & full-length trousers",
  "ageYears": 23,
  "heightMetres": 1.83,
  "clothes": "male_elegantsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "priya",
  "name": "Priya",
  "group": "staff",
  "role": "cashier",
  "detail": "Shop checkout \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 30,
  "heightMetres": 1.63,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "mateo",
  "name": "Mateo",
  "group": "staff",
  "role": "cashier",
  "detail": "Shop checkout \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 37,
  "heightMetres": 1.72,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "tessa",
  "name": "Tessa",
  "group": "staff",
  "role": "gardener",
  "detail": "Park team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 44,
  "heightMetres": 1.76,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "elias",
  "name": "Elias",
  "group": "staff",
  "role": "gardener",
  "detail": "Park team \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 51,
  "heightMetres": 1.84,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "poppy",
  "name": "Poppy",
  "group": "children",
  "role": "customer",
  "detail": "Age 5 \u00b7 Striped shirt & trousers",
  "ageYears": 5,
  "heightMetres": 1.02,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "finn",
  "name": "Finn",
  "group": "children",
  "role": "customer",
  "detail": "Age 6 \u00b7 Jacket & full-length jeans",
  "ageYears": 6,
  "heightMetres": 1.09,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "mila",
  "name": "Mila",
  "group": "children",
  "role": "customer",
  "detail": "Age 7 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 7,
  "heightMetres": 1.1,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "max",
  "name": "Max",
  "group": "children",
  "role": "customer",
  "detail": "Age 8 \u00b7 Striped shirt & trousers",
  "ageYears": 8,
  "heightMetres": 1.18,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "lily",
  "name": "Lily",
  "group": "children",
  "role": "customer",
  "detail": "Age 9 \u00b7 Jacket & full-length jeans",
  "ageYears": 9,
  "heightMetres": 1.23,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "arlo",
  "name": "Arlo",
  "group": "children",
  "role": "customer",
  "detail": "Age 10 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 10,
  "heightMetres": 1.28,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "nora",
  "name": "Nora",
  "group": "children",
  "role": "customer",
  "detail": "Age 11 \u00b7 Striped shirt & trousers",
  "ageYears": 11,
  "heightMetres": 1.31,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "jude",
  "name": "Jude",
  "group": "children",
  "role": "customer",
  "detail": "Age 12 \u00b7 Jacket & full-length jeans",
  "ageYears": 12,
  "heightMetres": 1.36,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ava",
  "name": "Ava",
  "group": "children",
  "role": "customer",
  "detail": "Age 13 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 13,
  "heightMetres": 1.39,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "kai",
  "name": "Kai",
  "group": "children",
  "role": "customer",
  "detail": "Age 14 \u00b7 Striped shirt & trousers",
  "ageYears": 14,
  "heightMetres": 1.51,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "isla",
  "name": "Isla",
  "group": "children",
  "role": "customer",
  "detail": "Age 15 \u00b7 Jacket & full-length jeans",
  "ageYears": 15,
  "heightMetres": 1.49,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "hassan",
  "name": "Hassan",
  "group": "children",
  "role": "customer",
  "detail": "Age 5 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 5,
  "heightMetres": 1.01,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ruby",
  "name": "Ruby",
  "group": "children",
  "role": "customer",
  "detail": "Age 6 \u00b7 Striped shirt & trousers",
  "ageYears": 6,
  "heightMetres": 0.99,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "haris",
  "name": "Haris",
  "group": "children",
  "role": "customer",
  "detail": "Age 7 \u00b7 Jacket & full-length jeans",
  "ageYears": 7,
  "heightMetres": 1.09,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "emma",
  "name": "Emma",
  "group": "children",
  "role": "customer",
  "detail": "Age 8 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 8,
  "heightMetres": 1.15,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "toby",
  "name": "Toby",
  "group": "children",
  "role": "customer",
  "detail": "Age 9 \u00b7 Striped shirt & trousers",
  "ageYears": 9,
  "heightMetres": 1.15,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ivy",
  "name": "Ivy",
  "group": "children",
  "role": "customer",
  "detail": "Age 10 \u00b7 Jacket & full-length jeans",
  "ageYears": 10,
  "heightMetres": 1.25,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "ryan",
  "name": "Ryan",
  "group": "children",
  "role": "customer",
  "detail": "Age 11 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 11,
  "heightMetres": 1.28,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "mina",
  "name": "Mina",
  "group": "children",
  "role": "customer",
  "detail": "Age 12 \u00b7 Striped shirt & trousers",
  "ageYears": 12,
  "heightMetres": 1.38,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "eli",
  "name": "Eli",
  "group": "children",
  "role": "customer",
  "detail": "Age 13 \u00b7 Jacket & full-length jeans",
  "ageYears": 13,
  "heightMetres": 1.45,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "zoe",
  "name": "Zoe",
  "group": "children",
  "role": "customer",
  "detail": "Age 14 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 14,
  "heightMetres": 1.5,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "aaron",
  "name": "Aaron",
  "group": "children",
  "role": "customer",
  "detail": "Age 15 \u00b7 Striped shirt & trousers",
  "ageYears": 15,
  "heightMetres": 1.56,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "mia",
  "name": "Mia",
  "group": "children",
  "role": "customer",
  "detail": "Age 5 \u00b7 Jacket & full-length jeans",
  "ageYears": 5,
  "heightMetres": 1.03,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "owen",
  "name": "Owen",
  "group": "children",
  "role": "customer",
  "detail": "Age 6 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 6,
  "heightMetres": 0.99,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "bella",
  "name": "Bella",
  "group": "children",
  "role": "customer",
  "detail": "Age 7 \u00b7 Striped shirt & trousers",
  "ageYears": 7,
  "heightMetres": 1.13,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "aiden",
  "name": "Aiden",
  "group": "children",
  "role": "customer",
  "detail": "Age 8 \u00b7 Jacket & full-length jeans",
  "ageYears": 8,
  "heightMetres": 1.1,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "sana",
  "name": "Sana",
  "group": "children",
  "role": "customer",
  "detail": "Age 9 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 9,
  "heightMetres": 1.16,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "dylan",
  "name": "Dylan",
  "group": "children",
  "role": "customer",
  "detail": "Age 10 \u00b7 Striped shirt & trousers",
  "ageYears": 10,
  "heightMetres": 1.2,
  "clothes": "male_casualsuit03",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "lucy",
  "name": "Lucy",
  "group": "children",
  "role": "customer",
  "detail": "Age 11 \u00b7 Jacket & full-length jeans",
  "ageYears": 11,
  "heightMetres": 1.28,
  "clothes": "male_casualsuit05",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 },
 {
  "id": "reuben",
  "name": "Reuben",
  "group": "children",
  "role": "customer",
  "detail": "Age 12 \u00b7 Long-sleeved shirt & trousers",
  "ageYears": 12,
  "heightMetres": 1.38,
  "clothes": "male_casualsuit01",
  "coverage": "long sleeves, covered torso, full-length trousers, closed shoes",
  "assetVersion": "covered-100-v1"
 }
];
