import {useState} from 'react';
import {Activity,FileText,Landmark} from 'lucide-react';
import {Account,Demo,PROPERTIES,financials,money,profit} from './model';

export type ReportData={incomeLabel?:string;offerCount?:number;capital?:number;period?:string;title:string;week:number;day:number;openingCash:number;openingCapital:number;wagesOwed:number;netProfit:number;rent:number;account:Pick<Account,'condition'|'purchases'|'cash'|'revenue'|'cogs'|'expenses'|'wages'|'paidWages'|'served'|'openingProperty'|'openingStock'|'research'|'units'|'items'|'reserve'>;figures:Pick<ReturnType<typeof financials>,'assets'|'liabilities'|'equity'|'stock'|'improvements'|'receivable'|'payable'|'operating'|'financing'|'closingCash'>};

/** One report component for every property: same arrangement as the restaurant console. */
export function FinancialConsole({state,id,data}:{state?:Demo;id:string;data?:ReportData}){
 const [mode,setMode]=useState<'statements'|'kpis'>('statements'),b=data?.account??state!.businesses[id],p={name:data?.title??PROPERTIES.find(p=>p.id===id)!.name},f=data?.figures??financials(state!,id),netProfit=data?.netProfit??profit(state!.businesses[id]),openingCash=data?.openingCash??25000,openingCapital=data?.openingCapital??25000+b.openingStock+b.openingProperty,wagesOwed=data?.wagesOwed??b.wages-b.paidWages;
 const row=(label:string,value:number,total=false,tone='')=><div className={`pc-row ${total?'pc-subtotal':''}`}><span>{label}</span><strong className={value<-.001?'pc-red':tone}>{money(value)}</strong></div>;
 const end=(label:string,value:number,tone='')=><div className="pc-end"><span>{label}</span><strong className={value<-.001?'pc-red':tone}>{money(value)}</strong></div>;
 return <section className="pc-console" aria-label={`${p.name} financial reports`}>
  <div className="pc-banner"><div className="pc-heading"><span className="pc-icon"><Landmark size={25}/></span><div><h3>Financial reporting & performance intelligence</h3><p>Sales, operating costs, cash and wages owed · {p.name}</p></div></div><div className="pc-subtabs" role="tablist" aria-label="Report type"><button role="tab" aria-selected={mode==='statements'} onClick={()=>setMode('statements')}><FileText size={16}/>Financial statements</button><button role="tab" aria-selected={mode==='kpis'} onClick={()=>setMode('kpis')}><Activity size={16}/>Operational KPIs</button></div></div>
  <div className="pc-stats">{[['Total revenue',money(b.revenue),'pc-green'],['Net operating profit',money(netProfit),netProfit<0?'pc-red':'pc-green'],[b.units.length?'Occupied units':'Orders served',b.units.length?`${b.units.filter(u=>u.occupied).length} / ${b.units.length}`:b.served,'pc-blue'],['Wages owed',money(wagesOwed),'pc-orange']].map(([label,value,color])=><article key={label}><span>{label}</span><strong className={color as string}>{value}</strong></article>)}</div>
  {mode==='statements'?<div className="pc-statements" role="tabpanel" aria-label="Financial statements">
   <article className="pc-panel"><div><h4>Profit & loss statement <span className={netProfit<0?'pc-red':'pc-green'}>{netProfit<0?'Deficit':'Profitable'}</span></h4><h5>Gross revenues</h5>{row(data?.incomeLabel??(id==='apartments'?'Rental income':id==='hotel'?'Guest room sales':id==='park'?'Kiosk & activity sales':'Customer sales'),b.revenue,false,'pc-green')}{row('Total net revenue',b.revenue,true,'pc-green')}<h5>Cost of goods sold (COGS)</h5>{row('Products & supplies consumed',-b.cogs)}{row('Gross margin',b.revenue-b.cogs,true,'pc-green')}<h5>Operating overhead (OPEX)</h5>{row('Staff wages earned',-b.wages)}{row('Recruitment, cleaning & repairs',-b.expenses)}{row('Property rent',-(data?.rent??0))}{row('Total overhead',-b.wages-b.expenses-(data?.rent??0),true)}</div>{end('Net operating profit',netProfit,'pc-green')}</article>
   <article className="pc-panel"><div><h4>Statement of cash flows <span className="pc-blue">Liquidity</span></h4>{row('Opening cash',openingCash,true)}<h5>Operating activities</h5>{row('Customer & tenant receipts',b.revenue)}{row('Inventory purchases',-b.purchases)}{row('Hiring & maintenance paid',-b.expenses)}{row('Staff wages paid',-b.paidWages)}{row('Property rent paid',-(data?.rent??0))}{row('Net operating cash',f.operating,true)}<h5>Investing activities (CAPEX)</h5>{row('Property improvements',-f.improvements)}{row('Recipe development',-b.research)}{row('Net investing cash',-f.improvements-b.research,true)}<h5>Financing activities</h5>{row('Net business loan movements',f.financing-(data?.capital??0))}{row('Additional contributed capital',data?.capital??0)}{row('Net financing cash',f.financing,true)}</div>{end('Closing cash treasury',f.closingCash,'pc-blue')}</article>
   <article className="pc-panel"><div><h4>This business balance sheet <span className="pc-green">{Math.abs(f.assets-f.liabilities-f.equity)<.02?'Balanced':'Review'}</span></h4><h5>This business assets</h5>{row('Cash on hand',b.cash,false,'pc-blue')}{row('Inventory stock (asset value)',f.stock,false,'pc-green')}{row('Property & opening equipment',b.openingProperty)}{row('Property improvements',f.improvements)}{row('Recipe collection assets',b.research)}{row('Loans receivable',f.receivable)}{row('Total valuation assets',f.assets,true,'pc-green')}<h5>Liabilities & shareholder equity</h5>{row('Unpaid wages',wagesOwed)}{row('Business loans payable',f.payable)}{row('Opening & contributed capital',openingCapital)}{row('Cumulative retained earnings',netProfit)}{row('Total owner’s book equity',f.equity,true)}</div>{end('Total liab. & equity',f.liabilities+f.equity)}</article>
  </div>:<div className="pc-kpis" role="tabpanel" aria-label="Operational KPIs">{[['Average transaction',money(b.served?b.revenue/b.served:0),'Receipts divided by service interactions.'],['Gross margin',`${b.revenue?Math.round((b.revenue-b.cogs)/b.revenue*100):0}%`,'Sales after products and supplies consumed.'],['Available offers',data?.offerCount??b.items.filter(i=>i.enabled).length,'Only selected offers are sold and automatically stocked.'],['Inventory at cost',money(f.stock),'Stock stays in this property’s account.'],['Property condition',`${b.condition}%`,'Clean and repair through Operations.'],['Cash reserve',money(b.reserve),'Minimum balance retained by the purchasing manager.']].map(([label,value,note])=><article className="pc-panel" key={label}><h4>{label}</h4><strong className="pc-blue pc-kpi-value">{value}</strong><p>{note}</p></article>)}</div>}
  <p className="pc-footnote">{data?.period??`Preview accounting period: Week 1 to Week ${state!.week}, Day ${state!.day}.`} Wages are paid on Day 4 of the next week. Each property has its own accounts; transfers are recorded as loans.</p>
 </section>;
}
