import {RECIPES,INGREDIENTS,type Recipe} from '../data/recipes';
import {PROPERTIES} from '../prototype/expansionModel';
export {PROPERTIES};
export type Item={id:string;name:string;category:string;cost:number;price:number;stock:number;enabled:boolean;color:string};
export type Role={name:string;count:number;wage:number;fee:number;detail:string};
export type Unit={occupied:boolean;dirty:boolean;rent:number;offer?:string;guest?:string};
export type Food={recipes:Recipe[];activeMenu:string[];inventory:Record<string,number>;batches:Record<string,{qty:number;costPerUnit:number}[]>};
export type Account={supplies?:Item[];food?:Food;research:number;cash:number;items:Item[];staff:Role[];units:Unit[];condition:number;upgrade:number;served:number;revenue:number;cogs:number;expenses:number;wages:number;paidWages:number;purchases:number;openingStock:number;openingProperty:number;ledger:{label:string;amount:number}[];manager:boolean;auto:boolean;budget:number;spent:number;reserve:number};
export type Demo={businesses:Record<string,Account>;week:number;day:number;loans:{from:string;to:string;amount:number;remaining:number}[];payroll:{id:string;amount:number;week:number}[];notice:string};
type Spec={subtitle:string;architecture:string;floors:string[];rooms:string[];loop:string[];verb:string;offerLabel:string;roles:[string,string];supplies:string[];palette:[string,string,string]};
export const SPECS:Record<string,Spec>={
 diner:{subtitle:'The familiar neighborhood restaurant',architecture:'Warm brick, timber floors, large street windows and copper details. Keep the close, playable restaurant view.',floors:['Dining room & kitchen'],rooms:['Dining room','Kitchen & pass','Pantry','Street terrace'],loop:['Choose dishes and prices','Order ingredients','Seat, cook and serve','Clear tables and review profit'],verb:'Serve a table',offerLabel:'Dishes',roles:['Chef','Waiter'],supplies:['Fresh ingredients','Drinks','Cleaning supplies'],palette:['#996049','#7b3c31','#d2b78c']},
 cafe:{subtitle:'A bright corner coffee house',architecture:'Cream plaster, dark green joinery, deep shop windows and a sheltered pavement terrace. Oak furniture and a visible espresso bar.',floors:['Coffee bar & seating'],rooms:['Espresso counter','Pastry display','Reading corner','Outdoor seating'],loop:['Choose drinks and pastries','Buy beans, milk and cups','Serve the morning queue','Clean and restock'],verb:'Serve a coffee order',offerLabel:'Dishes',roles:['Barista','Counter assistant'],supplies:['Coffee beans','Milk & pastries','Cups & napkins'],palette:['#c5bcaa','#34594c','#a98253']},
 bistro:{subtitle:'Seasonal dining beside the garden',architecture:'Weathered brick, dark olive frames, wine storage and a planted pergola. More intimate seating than the first diner.',floors:['Dining room & open kitchen'],rooms:['Dining room','Open kitchen','Wine cabinet','Garden terrace'],loop:['Create a seasonal menu','Source fresh ingredients','Run dinner service','Maintain quality and margins'],verb:'Serve a dinner table',offerLabel:'Dishes',roles:['Chef','Host / waiter'],supplies:['Fresh ingredients','Drinks','Kitchen supplies'],palette:['#92735a','#394d39','#bba17c']},
 hotel:{subtitle:'A small hotel with proper guest floors',architecture:'Stone frontage, recessed entrance, brass accents and warm window light. Reception occupies the ground floor; bedrooms are upstairs.',floors:['G · Reception & lounge','1 · Guest rooms 101–104','2 · Guest rooms 201–204'],rooms:['Reception & luggage','Lounge & concierge','Lift & stairs','Four rooms per guest floor'],loop:['Set nightly room rates','Check in arriving guests','Guests stay upstairs','Check out, clean and resell rooms'],verb:'Check in a guest',offerLabel:'Rooms',roles:['Receptionist','Housekeeper'],supplies:['Fresh linen','Guest toiletries','Cleaning supplies'],palette:['#b1a18b','#4b5152','#af9673']},
 apartments:{subtitle:'Homes above a shared ground-floor lobby',architecture:'Red-brown brick, inset balconies and individual front doors. A shared reception and mail room below two residential floors.',floors:['G · Lobby & property office','1 · Homes 101–103','2 · Homes 201–203'],rooms:['Leasing office','Mail & parcel room','Lift & stairs','Three homes per residential floor'],loop:['Set rents and list vacant homes','Accept a tenant','Collect weekly rent','Repair homes and renew leases'],verb:'Sign a tenant',offerLabel:'Homes',roles:['Leasing agent','Maintenance worker'],supplies:['Repair materials','Cleaning supplies','Safety supplies'],palette:['#865c48','#4e5b58','#b59972']},
 shop:{subtitle:'Choose what your neighborhood buys',architecture:'A glazed street-front store with brick piers, clear signage, stocked aisles and a separate stockroom. Visible products follow your selection.',floors:['Sales floor & stockroom'],rooms:['Product aisles','Produce display','Checkout','Stockroom'],loop:['Choose products for shelves','Order each product','Set prices and run checkout','Restock winners and remove slow sellers'],verb:'Complete a sale',offerLabel:'Products',roles:['Cashier','Stock assistant'],supplies:['Saleable stock','Packaging','Cleaning supplies'],palette:['#aa8d70','#40535c','#bd9b62']},
 park:{subtitle:'A public garden with a small business inside',architecture:'Mature trees, stone paths, a planted fountain courtyard and timber café pavilion. Admission stays free; kiosk sales and activities earn income.',floors:['Gardens, kiosk & facilities'],rooms:['Fountain courtyard','Refreshment kiosk','Picnic lawns','Gardener’s store'],loop:['Choose kiosk offers and activities','Buy supplies','Serve visitors and host activities','Maintain paths, plants and facilities'],verb:'Serve a park visitor',offerLabel:'Offers',roles:['Kiosk attendant','Groundskeeper'],supplies:['Refreshments','Garden supplies','Cleaning supplies'],palette:['#708455','#3d5b44','#bba17a']},
};
const item=(id:string,name:string,category:string,cost:number,price:number,color:string,enabled=true):Item=>({id,name,category,cost,price,color,enabled,stock:enabled?24:0});
export const catalogs:Record<string,Item[]>={
 diner:[item('burger','House burger','Main',4,12,'#a97544'),item('fries','Golden fries','Side',1,4,'#ddac53'),item('juice','Fresh juice','Drink',1.5,5,'#d69d43'),item('sushi','Basic sushi','Main',9,27,'#596d48',false),item('salad','Garden salad','Main',3,10,'#64854a',false),item('coffee','Black coffee','Drink',1,4,'#664c3b',false)],
 cafe:[item('coffee','Espresso','Coffee',1,4,'#694b3c'),item('latte','Oat milk latte','Coffee',1.8,6,'#b2946e'),item('croissant','Butter croissant','Bakery',1.5,5,'#bb8950'),item('sandwich','Cheese sandwich','Food',2.5,8,'#c6b576',false),item('tea','Garden tea','Tea',.8,4,'#718958',false),item('cake','Chocolate cake','Bakery',2,7,'#714c3a',false)],
 bistro:[item('chicken','Roast chicken','Main',6,19,'#aa7b49'),item('salad','Seasonal salad','Starter',3,10,'#789953'),item('wine','House red','Drink',4,11,'#713b40'),item('steak','Steak & greens','Main',10,29,'#9a6250',false),item('soup','Vegetable soup','Starter',2,8,'#b38556',false),item('dessert','Lemon tart','Dessert',2.5,9,'#d7c174',false)],
 shop:[item('apples','Fresh apples','Produce',1.2,3,'#b35740'),item('bread','Bakery bread','Bakery',1.5,4,'#bd925b'),item('milk','Milk cartons','Chilled',2,5,'#d0d8d9'),item('coffee','Coffee beans','Pantry',5,12,'#685242',false),item('soap','Hand soap','Household',1.8,5,'#75998a',false),item('flowers','Fresh flowers','Gifts',4,11,'#aa758b',false),item('cereal','Breakfast cereal','Pantry',3,8,'#b3a35a',false),item('chocolate','Chocolate bars','Snacks',1.5,4,'#785644',false)],
 hotel:[item('standard','Standard room','Per night',4,85,'#baa786'),item('suite','Corner suite','Per night',7,125,'#8d7763')],
 apartments:[item('studio','Studio apartment','Per week',2,180,'#baaa8b'),item('onebed','One-bedroom home','Per week',3,240,'#899985')],
 park:[item('coffee','Kiosk coffee','Refreshment',1,6,'#8c6d4d'),item('picnic','Picnic basket','Refreshment',4,12,'#a59656'),item('garden','Guided garden walk','Activity',1,18,'#69814d',false)],
};
export const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const supply=(id:string,name:string,category:string,cost:number,color:string):Item=>({...item(id,name,category,cost,cost,color),stock:30});
export const SUPPLY_CATALOGS:Record<string,Item[]>={
 hotel:[supply('linen','Fresh bed linen','Housekeeping',4,'#d3c9ad'),supply('towels','Bath towels','Housekeeping',2,'#cbc9bf'),supply('toiletries','Guest toiletries','Guest amenities',1.5,'#92a7a4'),supply('cleaner','Cleaning solution','Housekeeping',2,'#859d7a'),supply('tea','Tea & coffee tray','Guest amenities',1,'#9f895f'),supply('repair','Room repair kit','Maintenance',5,'#90785b')],
 apartments:[supply('paint','Paint & decorating','Maintenance',3,'#c5bdaa'),supply('repair','Repair materials','Maintenance',4,'#8d806b'),supply('cleaner','Cleaning supplies','Shared spaces',2,'#9aafa1'),supply('bulbs','Replacement lights','Electrical',1.5,'#c6b16d'),supply('safety','Safety supplies','Safety',2,'#a59c74')],
 park:[supply('refreshments','Kiosk refreshments','Kiosk',2,'#b89969'),supply('cups','Cups & packaging','Kiosk',.5,'#c2b699'),supply('garden','Plants & compost','Grounds',3,'#6e8552'),supply('cleaner','Cleaning supplies','Grounds',2,'#80967a'),supply('activity','Activity materials','Activities',1,'#a58e64')],
};
const SUPPLY_USE:Record<string,Record<string,number>>={standard:{linen:1,towels:1,toiletries:1},suite:{linen:1,towels:2,toiletries:2,tea:1},studio:{repair:1,cleaner:1},onebed:{repair:2,cleaner:1},coffee:{refreshments:1,cups:1},picnic:{refreshments:2,cups:2},garden:{activity:1}};
function syncSupplies(b:Account){for(const offer of b.items){const use=SUPPLY_USE[offer.id]??{refreshments:1,cups:1};offer.stock=Math.min(...Object.entries(use).map(([key,q])=>Math.floor((b.supplies!.find(s=>s.id===key)?.stock??0)/q)));offer.cost=Object.entries(use).reduce((n,[key,q])=>n+(b.supplies!.find(s=>s.id===key)?.cost??0)*q,0);}}
export function orderSupply(b:Account,id:string,qty=10){const i=b.supplies?.find(i=>i.id===id);if(!i||qty<=0||!Number.isInteger(qty)||b.cash<i.cost*qty)return 'Insufficient cash for this supply order.';i.stock+=qty;b.purchases+=i.cost*qty;entry(b,`${i.name} × ${qty}`,-i.cost*qty);syncSupplies(b);return `${qty} ${i.name} delivered to this property’s stockroom.`;}
function createFood(id:string):Food {
 const activeMenu=id==='cafe'?['coffee_black','recipe_65','juice_fruit']:id==='bistro'?['recipe_11','recipe_91','recipe_92']:['coffee_black','fries','juice_fruit'];
 const recipes=structuredClone(RECIPES).map(r=>({...r,unlocked:r.unlocked||activeMenu.includes(r.id)}));
 const ingredients=[...new Set(recipes.filter(r=>activeMenu.includes(r.id)).flatMap(r=>Object.keys(r.ingredients)))];
 const inventory=Object.fromEntries(ingredients.map(key=>[key,30]));
 return {recipes,activeMenu,inventory,batches:Object.fromEntries(ingredients.map(key=>[key,[{qty:30,costPerUnit:INGREDIENTS[key].cost}]]))};
}
function syncFood(b:Account){const f=b.food!;b.items=f.recipes.filter(r=>f.activeMenu.includes(r.id)).map(r=>({id:r.id,name:r.name,category:'Recipe',cost:Object.entries(r.ingredients).reduce((n,[id,q])=>n+INGREDIENTS[id].cost*q,0),price:r.price,stock:Math.min(...Object.entries(r.ingredients).map(([id,q])=>Math.floor((f.inventory[id]??0)/q))),enabled:true,color:'#a98b63'}));}
export function buyIngredient(b:Account,id:string,qty:number,discount=0){
 const f=b.food,ing=INGREDIENTS[id];if(!f||!ing||!Number.isInteger(qty)||qty<=0||![0,.1,.2,.3].includes(discount))return 'Invalid ingredient order.';
 const unitCost=ing.cost*(1-discount),cost=qty*unitCost;if(cost>b.cash)return 'This restaurant needs more cash to buy these ingredients.';
 f.inventory[id]=(f.inventory[id]??0)+qty;f.batches[id]=[...(f.batches[id]??[]),{qty,costPerUnit:unitCost}];b.purchases+=cost;entry(b,`${ing.name} × ${qty}`,-cost);syncFood(b);return `${qty} ${ing.name} delivered. Purchase cost saved in the FIFO pantry.`;
}
function autoFood(b:Account){
 const f=b.food!;const ingredients=[...new Set(f.recipes.filter(r=>f.activeMenu.includes(r.id)).flatMap(r=>Object.keys(r.ingredients)))];
 for(const id of ingredients){if((f.inventory[id]??0)>=10)continue;const cost=INGREDIENTS[id].cost;const qty=Math.max(0,Math.min(30-(f.inventory[id]??0),Math.floor((b.budget-b.spent)/cost),Math.floor((b.cash-b.reserve)/cost)));if(qty){buyIngredient(b,id,qty);b.spent+=qty*cost;}}
}
export function toggleRecipe(b:Account,id:string){const f=b.food!,r=f.recipes.find(r=>r.id===id);if(!r?.unlocked)return 'Unlock this recipe first.';const active=f.activeMenu.includes(id);if(active&&f.activeMenu.length===1)return 'Keep at least one dish on the menu.';if(!active&&f.activeMenu.length>=6)return 'Choose up to six dishes.';f.activeMenu=active?f.activeMenu.filter(key=>key!==id):[...f.activeMenu,id];autoOrder(b);return active?`${r.name} removed from this menu.`:`${r.name} added. Your manager orders its ingredients within budget.`;}
export function unlockRecipe(b:Account,id:string){const r=b.food!.recipes.find(r=>r.id===id);if(!r||r.unlocked||r.unlockCost>b.cash)return 'Recipe unavailable or insufficient cash.';r.unlocked=true;b.research+=r.unlockCost;entry(b,`Recipe unlocked · ${r.name}`,-r.unlockCost);return `${r.name} added to the recipe collection. Add it to your menu to serve it.`;}
export function priceRecipe(b:Account,id:string,price:number){const r=b.food!.recipes.find(r=>r.id===id);if(!r||!Number.isFinite(price)||price<r.basePrice||price>r.basePrice*3)return 'Price is outside the recipe range.';r.price=price;return `${r.name} menu price updated.`;}
export function updatePurchasing(b:Account,changes:Partial<Pick<Account,'auto'|'budget'|'reserve'>>){Object.assign(b,changes);autoOrder(b);return 'Purchasing rules updated. Orders respect this property’s budget and reserve.';}
export function payResearch(b:Account,cost:number){if(!b.food||cost!==2500||b.cash<cost)return 'Research requires $2,500 in this restaurant.';b.research+=cost;entry(b,'Research lab experiment',-cost);return 'Research funded by this restaurant. Choose your new recipe.';}
function serveFood(b:Account,id?:string){
 const f=b.food!,r=f.recipes.find(r=>f.activeMenu.includes(r.id)&&(!id||r.id===id));if(!r||Object.entries(r.ingredients).some(([key,q])=>(f.inventory[key]??0)<q))return 'Ingredients missing. Order them in the pantry first.';
 let cost=0;for(const[key,qty]of Object.entries(r.ingredients)){f.inventory[key]-=qty;let remaining=qty;while(remaining>0){const batch=f.batches[key][0],used=Math.min(remaining,batch.qty);cost+=used*batch.costPerUnit;remaining-=used;batch.qty-=used;if(batch.qty===0)f.batches[key].shift();}}
 b.cogs+=cost;b.revenue+=r.price;b.served++;b.condition=Math.max(0,b.condition-2);entry(b,`${r.name} · served`,r.price);autoOrder(b);return `${r.name} served for ${money(r.price)}. Actual ingredients consumed at FIFO cost ${money(cost)}.`;
}
export const stockValue=(b:Account)=>b.food?Object.values(b.food.batches).flat().reduce((n,i)=>n+i.qty*i.costPerUnit,0):(b.supplies??b.items).reduce((n,i)=>n+i.stock*i.cost,0);
export const wages=(b:Account)=>b.staff.reduce((n,r)=>n+r.count*r.wage,0)+(b.manager?60:0);
export const profit=(b:Account)=>b.revenue-b.cogs-b.expenses-b.wages;
export function createDemo():Demo {
 return {week:1,day:1,loans:[],payroll:[],notice:'Design sandbox ready. Each property has its own $25,000. Changes here never touch your game save.',businesses:Object.fromEntries(PROPERTIES.map(p=>{
  const items=structuredClone(catalogs[p.id]),openingStock=items.reduce((n,i)=>n+i.stock*i.cost,0);
  const b:Account={research:0,cash:25000,items,openingStock,openingProperty:p.buy||4500,staff:SPECS[p.id].roles.map((name,i)=>({name,count:1,wage:i?35:55,fee:120,detail:i?'Keeps service moving and the property ready.':'Handles routine service while you manage the neighborhood.'})),units:Array.from({length:p.id==='hotel'?8:p.id==='apartments'?6:0},()=>({occupied:false,dirty:false,rent:0})),condition:100,upgrade:0,served:0,revenue:0,cogs:0,expenses:0,wages:0,paidWages:0,purchases:0,ledger:[],manager:false,auto:true,budget:150,spent:0,reserve:500};if(['diner','cafe','bistro'].includes(p.id)){b.food=createFood(p.id);syncFood(b);b.openingStock=stockValue(b);b.staff.push({name:'Cleaner',count:0,wage:15,fee:90,detail:'Clears and cleans tables so new guests can be seated.'});}if(SUPPLY_CATALOGS[p.id]){b.supplies=structuredClone(SUPPLY_CATALOGS[p.id]);b.openingStock=stockValue(b);b.units.forEach((u,i)=>u.offer=p.id==='hotel'?(i%4===3?'suite':'standard'):(i%3===2?'onebed':'studio'));syncSupplies(b);}return[p.id,b];}))};
}
function entry(b:Account,label:string,amount:number){b.cash+=amount;b.ledger.unshift({label,amount});b.ledger=b.ledger.slice(0,30);}
export function transact(s:Demo,id:string,fn:(b:Account,next:Demo)=>string):Demo{const next=structuredClone(s);next.notice=fn(next.businesses[id],next);if(next.businesses[id].food)syncFood(next.businesses[id]);if(next.businesses[id].supplies)syncSupplies(next.businesses[id]);return next;}
function autoOrder(b:Account){if(!b.manager||!b.auto)return;if(b.food){autoFood(b);return;}if(b.supplies){for(const supply of b.supplies){if(supply.stock>=10)continue;const qty=Math.max(0,Math.min(30-supply.stock,Math.floor((b.budget-b.spent)/supply.cost),Math.floor((b.cash-b.reserve)/supply.cost)));if(qty){orderSupply(b,supply.id,qty);b.spent+=qty*supply.cost;}}return;}for(const i of b.items.filter(i=>i.enabled&&i.stock<10)){const qty=Math.max(0,Math.min(24-i.stock,Math.floor((b.budget-b.spent)/i.cost),Math.floor((b.cash-b.reserve)/i.cost)));if(qty){i.stock+=qty;b.spent+=qty*i.cost;b.purchases+=qty*i.cost;entry(b,`Manager ordered ${qty} × ${i.name}`,-qty*i.cost);}}}
export function order(b:Account,itemId:string,qty=10){const i=b.items.find(i=>i.id===itemId)!;const cost=i.cost*qty;if(b.cash<cost)return 'This business needs more cash to order.';i.stock+=qty;b.purchases+=cost;entry(b,`Ordered ${qty} × ${i.name}`,-cost);return `${qty} units of ${i.name} delivered to this business.`;}
export function toggleItem(b:Account,id:string){const i=b.items.find(i=>i.id===id)!;if(i.enabled&&b.items.filter(i=>i.enabled).length===1)return 'Keep at least one offer available.';if(!i.enabled&&b.items.filter(i=>i.enabled).length>=6)return 'Six display slots are available. Remove one product first.';i.enabled=!i.enabled;autoOrder(b);return i.enabled?`${i.name} is available. Your purchasing manager can order it.`:`${i.name} removed from sale. Existing stock stays in the stockroom.`;}
export function serve(b:Account,id:string,chosen?:string){
 if(b.food)return serveFood(b,chosen);
 const i=b.items.find(i=>i.enabled&&i.stock>0&&(!chosen||i.id===chosen));if(!i)return 'Choose an available offer and order its supplies first.';
 const unit=b.units.find(u=>!u.occupied&&!u.dirty&&(!u.offer||u.offer===i.id));if(b.units.length&&!unit)return 'All units are occupied or need care. Free and prepare a unit first.';
 if(b.supplies){for(const[key,q]of Object.entries(SUPPLY_USE[i.id]??{refreshments:1,cups:1})){const supply=b.supplies.find(s=>s.id===key)!;supply.stock-=q;b.cogs+=supply.cost*q;}}else{i.stock--;b.cogs+=i.cost;}b.revenue+=i.price;b.served++;b.condition=Math.max(0,b.condition-2);entry(b,`${i.name} · customer payment`,i.price);if(unit){unit.occupied=true;unit.rent=i.price;unit.guest=['Taylor Reed','Alex Morgan','Jordan Lee','Sam Patel','Casey Miller','Robin Chen'][b.served%6];}autoOrder(b);
 return `${SPECS[id].verb}: ${money(i.price)} received in this property’s account.`;
}
export function clean(b:Account,index?:number){if(b.cash<15)return 'This business needs $15 for supplies and maintenance.';if(index!==undefined)b.units[index].dirty=false;else{b.units.forEach(u=>u.dirty=false);b.condition=100;}b.expenses+=15;entry(b,'Cleaning / repair service',-15);return 'Space prepared. Maintenance cost recorded in this business’s P&L.';}
export function hire(b:Account,index:number){const r=b.staff[index];if(r.count>=4||b.cash<r.fee)return 'The team is full or needs more cash.';r.count++;b.expenses+=r.fee;entry(b,`Hired ${r.name}`,-r.fee);return `${r.name} hired. Weekly wages updated.`;}
export function hireManager(b:Account){if(b.manager||b.cash<250)return 'A manager is already hired or cash is too low.';b.manager=true;b.expenses+=250;entry(b,'Purchasing manager hired',-250);autoOrder(b);return 'Manager hired. Selected offers are restocked within this account’s budget and reserve.';}
export function upgrade(b:Account){const cost=600*(b.upgrade+1);if(b.upgrade>=3||b.cash<cost)return 'Upgrade unavailable.';b.upgrade++;entry(b,`Property improvement ${b.upgrade}`,-cost);return 'Upgrade installed. This is an asset, not a P&L expense.';}
export function transfer(s:Demo,from:string,to:string,amount:number):Demo {if(!s.businesses[from]||!s.businesses[to]||from===to||!Number.isFinite(amount)||amount<=0||s.businesses[from].cash<amount)return{...s,notice:'Choose two businesses and an amount the lender can afford.'};const next=structuredClone(s);entry(next.businesses[from],`Loan to ${PROPERTIES.find(p=>p.id===to)!.name}`,-amount);entry(next.businesses[to],`Loan from ${PROPERTIES.find(p=>p.id===from)!.name}`,amount);next.loans.push({from,to,amount,remaining:amount});next.notice=`${money(amount)} transferred as a repayable loan. No shared wallet.`;return next;}
export function repay(s:Demo,index:number):Demo {const next=structuredClone(s),l=next.loans[index];if(!l||next.businesses[l.to].cash<l.remaining)return{...s,notice:'Borrower needs enough cash to repay.'};entry(next.businesses[l.to],'Business loan repayment',-l.remaining);entry(next.businesses[l.from],'Loan repayment received',l.remaining);l.remaining=0;next.notice='Loan repaid. Both accounts and balance sheets updated.';return next;}
export function nextDay(s:Demo):Demo {
 const next=structuredClone(s);next.day++;if(next.day===8){next.day=1;next.week++;for(const[id,b]of Object.entries(next.businesses)){const pay=wages(b);b.wages+=pay;next.payroll.push({id,amount:pay,week:next.week});b.spent=0;if(id==='apartments'){const rent=b.units.filter(u=>u.occupied).reduce((n,u)=>n+u.rent,0);if(rent){b.revenue+=rent;entry(b,'Weekly tenant rent',rent);}}autoOrder(b);}}
 if(next.day===4){for(const pay of next.payroll.filter(p=>p.week<=next.week)){const b=next.businesses[pay.id];b.paidWages+=pay.amount;entry(b,'Payday · previous week’s wages',-pay.amount);}next.payroll=next.payroll.filter(p=>p.week>next.week);}
 next.notice=`Week ${next.week}, Day ${next.day}. Wages accrue at week end and are paid on Day 4 of the following week.`;return next;
}
export function financials(s:Demo,id:string){const b=s.businesses[id],receivable=s.loans.filter(l=>l.from===id).reduce((n,l)=>n+l.remaining,0),payable=s.loans.filter(l=>l.to===id).reduce((n,l)=>n+l.remaining,0),improvements=600*b.upgrade*(b.upgrade+1)/2,stock=stockValue(b),assets=b.cash+stock+b.openingProperty+improvements+b.research+receivable,liabilities=payable+b.wages-b.paidWages,equity=25000+b.openingStock+b.openingProperty+profit(b),operating=b.revenue-b.purchases-b.expenses-b.paidWages,financing=payable-receivable;return{receivable,payable,improvements,stock,assets,liabilities,equity,operating,financing,closingCash:25000+operating-improvements-b.research+financing};}
