import {RecipesModal} from '../components/RecipesModal';
import {InventoryModal} from '../components/InventoryModal';
import {useState} from 'react';
import {ResearchLabModal} from '../components/ResearchLabModal';
import {Account,Demo,buyIngredient,toggleRecipe,unlockRecipe,priceRecipe,transact,updatePurchasing,payResearch} from './model';
export function RestaurantManagement({id,b,section,onChange}:{id:string;b:Account;section:'offers'|'inventory';onChange:React.Dispatch<React.SetStateAction<Demo>>}){
 const f=b.food!;const act=(update:(account:Account)=>string)=>onChange(s=>transact(s,id,update));const[lab,setLab]=useState(false);
 return <div className="pv-native game-ui" key={`${id}-${section}`}>
 {section==='offers'?<><div className="pc-subtabs" style={{marginBottom:16}}><button onClick={()=>setLab(false)} aria-pressed={!lab}>Recipes & menu</button><button onClick={()=>setLab(true)} aria-pressed={lab}>Research lab</button></div>{lab?<ResearchLabModal money={b.cash} existingRecipesCount={f.recipes.length} onPayResearchCost={cost=>act(a=>payResearch(a,cost))} onAddCustomRecipe={recipe=>act(a=>{a.food!.recipes.push(recipe);return `${recipe.name} added to this restaurant’s collection.`;})}/>:<RecipesModal recipes={f.recipes} inventory={f.inventory} money={b.cash} activeMenu={f.activeMenu} hasManager={b.manager} manager={{enabled:b.auto,target:30,budget:b.budget,spent:b.spent,reserve:b.reserve}} onToggleActive={key=>act(a=>toggleRecipe(a,key))} onUnlockRecipe={key=>act(a=>unlockRecipe(a,key))} onChangePrice={(key,price)=>act(a=>priceRecipe(a,key,price))}/>}</>:<><InventoryModal inventory={f.inventory} inventoryBatches={f.batches} money={b.cash} unlockedRecipes={f.recipes.filter(r=>f.activeMenu.includes(r.id))} onBuyIngredient={(key,qty,discount)=>act(a=>buyIngredient(a,key,qty,discount))}/>{b.manager&&<section className="pv-manager"><h4>Purchasing manager rules</h4><label className="pv-check"><input type="checkbox" checked={b.auto} onChange={e=>act(a=>updatePurchasing(a,{auto:e.target.checked}))}/> Automatic ingredient orders</label><div className="pv-split"><label>Weekly budget<select aria-label="Restaurant manager budget" value={b.budget} onChange={e=>act(a=>updatePurchasing(a,{budget:Number(e.target.value)}))}>{[50,150,300,600].map(n=><option key={n} value={n}>${n}</option>)}</select></label><label>Keep in this account<select aria-label="Restaurant manager reserve" value={b.reserve} onChange={e=>act(a=>updatePurchasing(a,{reserve:Number(e.target.value)}))}>{[0,150,500,1000,5000].map(n=><option key={n} value={n}>${n}</option>)}</select></label></div></section>}</>}
 </div>;
}
