import {useState} from 'react';
import {Business,ExpansionState,hireBusinessStaff,Property} from '../prototype/expansionModel';
import {APARTMENT_FLOORS,apartmentFloorChecks,apartmentFloorBlocker,apartmentWeeks,FURNISHING_PACKAGES,FurnishingPackage,apartmentTerm,tenantDepositWeeks} from './apartments';
import {LodgingAction,LodgingBooking,roomLabel,shiftActive,StaffShift} from './lodging';
import {UnlockDetails} from '../components/UnlockDetails';
const cash=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
type Props={p:Property;b:Business;state:ExpansionState;act:(a:LodgingAction)=>void};
export function ApartmentFloors({p,b,state,act}:Props){
 return <><h3>Apartments · ten floors of homes</h3><article className="mc-inner-panel lodging-issue"><h3>Included: G + Floor 1</h3><p>G has the leasing office, mail and parcels, lobby, maintenance store and lift. Floor 1 has <b>three studios, each with a kitchen, bathroom and living area</b>. Residents stay on six-, twelve- or twenty-four-week leases.</p><p><b>{apartmentWeeks(b)} occupied-home weeks</b> earned. Each home contributes one point for every full week occupied. Keeping residents, maintaining homes and collecting rent drive expansion.</p></article><div className="lodging-room-grid">{APARTMENT_FLOORS.map(f=>{const open=f.floor<=b.lodging!.openFloors,next=f.floor===b.lodging!.openFloors+1,checks=apartmentFloorChecks(p,b,state,f.floor);return <article className="mc-inner-panel lodging-room" key={f.floor}><div className="lodging-card-title"><h3>Floor {f.floor} · {f.name}</h3><b>{open?'Open':next?'Next expansion':'Locked'}</b></div><p>Homes {f.floor}01–{f.floor}03 · {f.floor*3} homes in total</p>{!open&&<ul className="lodging-checklist">{checks.map(c=><li key={c.label} data-ready={c.met}>{c.met?'✓':'○'} {c.label}<b>{c.value}</b></li>)}</ul>}<UnlockDetails visible={(f.floor===1?'':'Three additional studio homes. ')+f.visible} milestone={open?'Already open':checks.map(c=>c.label).join(' · ')} cost={f.cost?cash(f.cost):'Opening package included'} stockCost={f.cost?25:0} addedWages={f.cost?35:0} recurring="No floor fee. Additional staff cost $35/week plus $120 to hire. Optional amenities have their own weekly upkeep." needs="Stock landlord cleaning, repair, plumbing and appliance supplies. Tenants buy their own groceries. Suggested extra starting supplies: $25, purchased separately." next={f.floor<10?'Keep homes occupied and prepare for Floor '+(f.floor+1)+'.':'Thirty homes open; consider top-floor penthouses and resident facilities.'}/><button className={open?'mc-button':'mc-button-green'} disabled={open||!next||!!apartmentFloorBlocker(p,b,state)||b.cash<f.cost} onClick={()=>act({type:'floor'})}>{open?'Open':next?`Open floor ${f.floor} · ${cash(f.cost)}`:'Open previous floors first'}</button></article>;})}</div></>;
}
export function ApartmentLeaseTerms({b,act}:Pick<Props,'b'|'act'>){
 const l=b.lodging!,active=l.bookings.filter(v=>v.status==='staying');
 return <article className="mc-inner-panel lodging-issue"><h3>Terms for new applications</h3><label>Lease length<select aria-label="New apartment lease length" value={apartmentTerm(b)} onChange={e=>act({type:'leaseTerms',weeks:Number(e.target.value) as 6|12|24,depositWeeks:tenantDepositWeeks(b)})}>{[6,12,24].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></label><label>Refundable deposit<select aria-label="Apartment deposit policy" value={tenantDepositWeeks(b)} onChange={e=>act({type:'leaseTerms',weeks:apartmentTerm(b),depositWeeks:Number(e.target.value) as 0|1})}><option value={1}>One week of agreed rent</option><option value={0}>No deposit</option></select></label><p>Terms are fixed when an applicant reserves a home. Weekly rent is collected automatically. Deposits stay separate from income and are refunded after move-out; purchasing protects this cash.</p><p>{active.filter(v=>v.noticeGiven).length} upcoming vacancies or renewals to review · {l.renewalsAccepted??0}/{l.renewalsOffered??0} renewal offers accepted. Review expiring leases below.</p></article>;
}
export function ApartmentRenewal({booking,b,week,act}:{booking:LodgingBooking;b:Business;week:number;act:(a:LodgingAction)=>void}){
 const [rate,setRate]=useState(String(booking.rate)),[term,setTerm]=useState<6|12|24>(apartmentTerm(b));
 if(booking.status!=='staying')return null;
 if(booking.renewal)return <p>{booking.renewal.accepted?`Renewal agreed: ${cash(booking.renewal.rate)}/week for ${booking.renewal.weeks} weeks, beginning when the current lease ends.`:'Renewal declined · resident will move out at lease end.'}</p>;
 if((booking.leaseEnd??Infinity)>week+1)return <p>Renewal offers open during the final week. Current rent remains {cash(booking.rate)}/week.</p>;
 return <div className="lodging-renewal"><p><b>Lease ending · Week {booking.leaseEnd}.</b> Offer a renewal, or let the resident move out. High rents and low satisfaction make rejection more likely.</p><label>Renewal rent<input aria-label={`Renewal rent ${booking.id}`} type="number" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Renewal term<select aria-label={`Renewal term ${booking.id}`} value={term} onChange={e=>setTerm(Number(e.target.value) as 6|12|24)}>{[6,12,24].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></label><button className="mc-button-green" disabled={!Number.isFinite(Number(rate))||Number(rate)<=0} onClick={()=>act({type:'renew',id:booking.id,rate:Number(rate),weeks:term})}>Offer renewal</button></div>;
}
export function ApartmentFurnishing({b,index,act}:{b:Business;index:number;act:(a:LodgingAction)=>void}){
 const u=b.venue!.units[index],[choice,setChoice]=useState<FurnishingPackage>(u.furnishing??'furnished'),pack=FURNISHING_PACKAGES.find(f=>f.id===choice)!;
 return <><label>Furnishing package<select aria-label={`${roomLabel({kind:'apartments'} as Property,index)} furnishing`} value={choice} onChange={e=>setChoice(e.target.value as FurnishingPackage)}>{FURNISHING_PACKAGES.map(f=><option key={f.id} value={f.id}>{f.name} · {cash(f.cost)}</option>)}</select></label><p>{pack.description} Suggested rent: {Math.round(pack.rent*100)}% of the home type’s base. Resident-owned furniture appears after move-in.</p><button className="mc-button" disabled={choice===(u.furnishing??'furnished')||u.occupied||b.cash<pack.cost||b.lodging!.bookings.some(v=>v.unit===index&&['reserved','waiting'].includes(v.status))} onClick={()=>act({type:'furnish',unit:index,package:choice})}>{choice===(u.furnishing??'furnished')?'Package installed':`Apply package · ${cash(pack.cost)}`}</button><p>Premium fittings unlock with Floor 8: upgraded floor finish and fixtures, +12% suggested asking rent.</p><button className="mc-button" disabled={!!u.premiumFinish||b.lodging!.openFloors<8||u.occupied||b.cash<650||b.lodging!.bookings.some(v=>v.unit===index&&['reserved','waiting'].includes(v.status))} onClick={()=>act({type:'finish',unit:index})}>{u.premiumFinish?'Premium fittings installed':'Premium fittings · $650'}</button></>;
}
export function ApartmentExtraStaff({p,b,onChange,act}:{p:Property;b:Business;onChange:(f:(s:ExpansionState)=>ExpansionState)=>void;act:(a:LodgingAction)=>void}){
 return <>{(['cleaner','supervisor'] as const).map(role=><article className="mc-inner-panel lodging-staff" key={role}><div className="lodging-card-title"><h3>{role==='cleaner'?'Residential cleaner':'Building supervisor'}</h3><b>{b.hires?.[role]??0} on team · {shiftActive(b,role)?'On shift':'Off shift'}</b></div><p>{role==='cleaner'?'Adds turnover and common-area cleaning capacity; uses cleaning supplies.':'Resolves resident service and noise complaints. The purchasing manager orders stock; technicians repair faults.'}</p><label>Daily shift<select aria-label={`${role} shift`} value={b.lodging!.shifts[role]??'all'} onChange={e=>act({type:'shift',role,shift:e.target.value as StaffShift})}><option value="all">All-day rota</option><option value="morning">Morning · 06:00–14:00</option><option value="afternoon">Afternoon · 14:00–22:00</option><option value="evening">Night · 22:00–06:00</option></select></label><button className="mc-button-green" disabled={(b.hires?.[role]??0)>=8||b.cash<120} onClick={()=>onChange(s=>hireBusinessStaff(s,p.id,role))}>Hire · $120 + $35/week</button></article>)}</>;
}
