import {useState} from 'react';
import {ExpansionState,Property,PROPERTIES,propertyById,lendCash,loanRepayment,repayLoan,refinanceLoan} from '../prototype/expansionModel';
import type {GameState} from '../hooks/useGameLoop';
import {protectedObligations} from './cashProtection';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD'});
export function BusinessLoans({state,p,restaurant,onChange}:{state:ExpansionState;p:Property;restaurant?:GameState;onChange:(f:(s:ExpansionState)=>ExpansionState)=>void}){
 const sources=Object.keys(state.businesses).filter(id=>id!==p.id).map(id=>propertyById(id)!),b=state.businesses[p.id];
 const [source,setSource]=useState(sources[0]?.id??''),[amount,setAmount]=useState(250),[term,setTerm]=useState<10|20|40>(10),[purpose,setPurpose]=useState<'operating'|'property'>('operating'),[terms,setTerms]=useState<Record<string,10|20|40>>({});
 const protection=protectedObligations(p,b,state,restaurant),buffer=restaurant?.manager.reserve??b.manager?.reserve??0;
 const nextDay=state.day===7?`Week ${state.week+1}, Day 1`:`Week ${state.week}, Day ${state.day+1}`;
 const loans=state.loans.filter(l=>(l.to===p.id||l.from===p.id)&&l.outstanding>0);
 return <section aria-label="Business finance" className="space-y-4">
  <div className="management-summary"><strong>Automatic payments · separate accounts</strong><span>Interest-free instalments on Day 4. Rent at week end. Unpaid balances retry each game day; no automatic borrowing or property seizure.</span></div>
  <article className="mc-inner-panel p-4"><h3>Protected cash</h3><p>Wages owed {money(protection.wages)} · scheduled rent {money(protection.rent)} · loans due / next instalment {money(protection.loans)} · refundable deposits {money(protection.deposits)} · service upkeep {money(protection.upkeep??0)} · return reserve {money(protection.returnReserve??0)}.</p><p>Player buffer {money(buffer)} · total protected <strong>{money(protection.total+buffer)}</strong> · free for purchasing <strong>{money(Math.max(0,b.cash-protection.total-buffer))}</strong>.</p><small>Wages accrue as the week runs. Future unearned wages and uncertain sales are not counted as cash.</small></article>
  <article className="loan-card"><strong>Property rent / lease</strong><span>{b.tenure==='leased'?`${money(p.rent)} per week`:'Owned · no property rent'}</span>{(b.leaseDue??0)>0&&<p role="status">Rent arrears: {money(b.leaseDue!)}. Next retry: {nextDay}.</p>}</article>
  {protection.arrears>0&&<article className="mc-inner-panel p-4" role="status"><strong>Recovery plan · {money(protection.arrears)} overdue</strong><p>Overdue wages {money(protection.wageArrears??0)} · next retry {nextDay}.</p><p>Manager orders are limited to cash above obligations and your buffer. Sell existing stock, reduce slow-selling menu items and postpone expansion. New receipts repay arrears on the next daily retry. You can repay early or explicitly refinance a loan below.</p></article>}
  {!!sources.length&&<div className="loan-form"><strong>Borrow from another business</strong><label>Lender<select aria-label="Loan lender" value={source} onChange={e=>setSource(e.target.value)}>{sources.map(x=><option key={x.id} value={x.id}>{x.name} · {money(state.businesses[x.id].cash)}</option>)}</select></label><label>Purpose<select aria-label="Loan purpose" value={purpose} onChange={e=>{const v=e.target.value as typeof purpose;setPurpose(v);setTerm(v==='operating'?10:40);}}><option value="operating">Operating · stock and wages</option><option value="property">Property · acquisition and improvements</option></select></label><label>Amount<input aria-label="Loan amount" type="number" min="1" step="25" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Term<select aria-label="Loan term" value={term} onChange={e=>setTerm(Number(e.target.value) as typeof term)}>{[10,20,40].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></label><p>{money(Math.ceil(amount/term*100)/100)} weekly from Week {state.week+1}, Day 4. Total principal {money(amount)}; no interest.</p><button className="primary wide" disabled={!Number.isFinite(amount)||amount<=0||amount>(state.businesses[source]?.cash??0)} onClick={()=>onChange(s=>lendCash(s,source,p.id,amount,term,purpose))}>Transfer as a loan</button></div>}
  {loans.map(l=>{const schedule=loanRepayment(l,state.week),newTerm=terms[l.id]??20;return <article className="loan-card" key={l.id}><strong>{l.to===p.id?'Owed to':'Lent to'} {propertyById(l.to===p.id?l.from:l.to)?.name}</strong><span>{l.purpose??'Existing'} loan · {l.term?`${l.term} weeks`:'original schedule preserved'} · {money(l.outstanding)} outstanding</span><small>{money(Math.min(l.outstanding,schedule.weeklyAmount))} / week · next Week {Math.max(schedule.startWeek,schedule.lastScheduledWeek+1)}, Day 4</small>{schedule.due>0&&<p role="status">Arrears {money(schedule.due)} · next retry {nextDay}.</p>}{l.to===p.id&&<><div><button disabled={b.cash<Math.min(100,l.outstanding)} onClick={()=>onChange(s=>repayLoan(s,l.id,Math.min(100,l.outstanding)))}>Pay extra {money(Math.min(100,l.outstanding))}</button><button disabled={b.cash<l.outstanding} onClick={()=>onChange(s=>repayLoan(s,l.id,l.outstanding))}>Repay in full</button></div><details><summary>Refinance remaining balance</summary><select aria-label={`Refinance ${l.id} term`} value={newTerm} onChange={e=>setTerms({...terms,[l.id]:Number(e.target.value) as 10|20|40})}>{[10,20,40].map(n=><option key={n} value={n}>{n} weeks</option>)}</select><p>{money(l.outstanding)} including arrears becomes {money(Math.ceil(l.outstanding/newTerm*100)/100)} / week, starting Week {state.week+1}, Day 4. No new cash, interest or fees.</p><button onClick={()=>onChange(s=>refinanceLoan(s,l.id,newTerm))}>Apply this repayment schedule</button></details></>}</article>})}
  {!loans.length&&<p>No outstanding loans.</p>}
  <h3>Recent cash movements</h3><div className="cash-ledger">{[...b.ledger].reverse().slice(0,8).map((e,i)=><div key={i}><span>{e.label}<small>Week {e.week}, Day {e.day}</small></span><strong>{money(e.amount)}</strong></div>)}</div>
 </section>;
}
