import {useState} from 'react';
import {Business,ExpansionState,Property} from '../prototype/expansionModel';
import {retailOrderCost,retailOrderDiscount,retailDisplayCapacity,placeAllRetailProducts,availableRetailProducts,retailShelfCount,retailProductFloor,retailSelectionDisabled,retailPrice,setProductPrice,setShelfProduct,orderRetailStock} from './retail';
import {changeOffer,offersFor,offerPrice,offerEnabled} from './businessOffers';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
export function BusinessCatalog({p,b,onChange,inventory=false}:{p:Property;b:Business;onChange:(fn:(s:ExpansionState)=>ExpansionState)=>void;inventory?:boolean}){
  const [category,setCategory]=useState('All'),[quantity,setQuantity]=useState(10);
  if(b.retail)return <section aria-label={inventory?'Supermarket inventory':'Supermarket product selection'} className="business-catalog">
    <div className="catalog-heading"><div><h3>{inventory?'Order products for your supermarket':'Choose what your supermarket sells'}</h3><p>{retailShelfCount(b,0)}/{retailDisplayCapacity(0)} grocery displays{b.retail.electronicsUnlocked?` · ${retailShelfCount(b,1)}/${retailDisplayCapacity(1)} electronics displays`:' · Electronics floor locked — open it in Upgrades'} · stock remains in the stockroom when removed from display.</p></div><label>Order quantity<select aria-label="Product order quantity" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}>{[1,3,5,10,25,50].map(n=><option key={n} value={n}>{n} units</option>)}</select></label></div>
    <div className="flex flex-wrap gap-2 my-2"><button className="mc-button" disabled={retailShelfCount(b,0)===retailDisplayCapacity(0)} onClick={()=>onChange(s=>placeAllRetailProducts(s,p.id,0))}>Place all groceries</button>{b.retail!.electronicsUnlocked&&<button className="mc-button" disabled={retailShelfCount(b,1)===retailDisplayCapacity(1)} onClick={()=>onChange(s=>placeAllRetailProducts(s,p.id,1))}>Place all electronics</button>}</div>
    <div className="catalog-filters" aria-label="Product categories">{['All',...new Set(availableRetailProducts(b).map(item=>item.category))].map(name=><button key={name} aria-pressed={category===name} onClick={()=>setCategory(name)}>{name}</button>)}</div>
    <div className="catalog-grid">{availableRetailProducts(b).filter(item=>category==='All'||item.category===category).map(item=>{
      const price=retailPrice(b,item.id),stock=b.retail!.stock[item.id]??0,selected=b.retail!.shelves.includes(item.id),qty=Math.min(quantity,100-stock);
      return <article key={item.id} className="catalog-card"><div className="catalog-title"><span className="catalog-art" style={{background:`${item.color}33`}}>{item.icon}</span><div><small>{retailProductFloor(item.id)===1?'Floor 1 · ':'Ground · '}{item.category}</small><h4>{item.name}</h4><span>{stock} units in stock {selected?'· on display':'· not displayed'}</span></div></div>
        <div className="catalog-costs"><span>Unit cost<b>{money(item.cost)}</b></span><span>Unit profit<b>{money(price-item.cost)}</b></span><span>Margin<b>{Math.round((price-item.cost)/price*100)}%</b></span></div>
        <label className="catalog-price">Selling price <input aria-label={`${item.name} selling price`} type="number" min={item.cost} max={item.price*3} step="0.5" value={price} onChange={e=>onChange(s=>setProductPrice(s,p.id,item.id,Number(e.target.value)))}/></label>
        <p>{Math.round(Math.exp(-2.5*Math.max(0,price/item.price-1))*100)}% demand at this price</p>
        <button className={selected?'catalog-selected':'primary'} disabled={retailSelectionDisabled(b,item.id)} onClick={()=>onChange(s=>setShelfProduct(s,p.id,item.id))}>{selected?'Remove from shelves':'Place on shelves'}</button>
        <button className="secondary" disabled={!qty||b.cash<retailOrderCost(item.id,qty)} onClick={()=>onChange(s=>orderRetailStock(s,p.id,item.id,quantity))}>{qty?`Order ${qty} · ${money(retailOrderCost(item.id,qty))}${retailOrderDiscount(item.id,qty)?` · ${Math.round(retailOrderDiscount(item.id,qty)*100)}% off`:""}`:'Stockroom full'}</button>
      </article>;
    })}</div>
    <p className="catalog-note">Your purchasing manager reorders selected groceries up to 30 units and electronics up to 3 units, within this supermarket’s budget and cash reserve.</p>
  </section>;
  return <section className="business-catalog" aria-label="Offers and prices"><div className="catalog-heading"><div><h3>{p.kind==='hotel'?'Rooms & nightly rates':p.kind==='apartments'?'Homes & weekly rent':'Kiosk menu & activities'}</h3><p>Choose your offers and prices. Higher prices reduce demand. Keep at least one offer available.</p></div></div><div className="catalog-grid">{offersFor(p).map(offer=>{const price=offerPrice(b,offer),enabled=offerEnabled(b,offer.id);return <article className="catalog-card" key={offer.id}><div className="catalog-title"><span className="catalog-art">{offer.icon}</span><h4>{offer.name}</h4></div><p>{offer.description}</p><label className="catalog-price">{p.kind==='apartments'?'Weekly rent':'Price'}<input aria-label={`${offer.name} price`} type="number" min={offer.price*.5} max={offer.price*3} step={p.kind==='park'?1:5} value={price} onChange={e=>onChange(s=>changeOffer(s,p.id,offer.id,{price:Number(e.target.value)},p))}/></label><p>{Math.round(Math.exp(-2.5*Math.max(0,price/offer.price-1))*100)}% demand at this price</p><button className={enabled?'catalog-selected':'primary'} disabled={enabled&&offersFor(p).filter(item=>offerEnabled(b,item.id)).length===1} onClick={()=>onChange(s=>changeOffer(s,p.id,offer.id,{enabled:!enabled},p))}>{enabled?'Available · take off sale':'Make available'}</button></article>;})}</div>{p.kind==='apartments'&&<p className="catalog-note">New rent applies to new leases. Existing tenants keep their agreed rent, collected at the start of each week.</p>}</section>;
}
