import {Business,ExpansionState,hireBusinessStaff,Property} from '../prototype/expansionModel';
import {UnlockDetails} from '../components/UnlockDetails';
import {HOTEL_FLOORS,hotelCompletedNights,hotelFloorChecks,hotelFloorBlocker} from './hotelProgression';
import {LodgingAction,hotelWeeklyUpkeep,shiftActive,StaffShift,roomLabel} from './lodging';
import {laundryPending,laundryQuantity} from './hotelLaundry';
const cash=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
type Props={p:Property;b:Business;state:ExpansionState;act:(a:LodgingAction)=>void};
export function HotelFloors({b,state,act}:Props){
 const l=b.lodging!;
 return <><h3>Hotel growth · G + five guest floors</h3><article className="mc-inner-panel lodging-issue"><h3>Included at opening: G + Floor 1</h3><p><b>G:</b> reception, waiting lounge, luggage, staff office, public toilets and lift. Guests sleep upstairs in <b>Rooms 101–104 on Floor 1</b>. Each room has its own bathroom.</p><p>{hotelCompletedNights(b)} completed room-nights · {l.profitableWeeks??0} consecutive profitable weeks · {b.venue!.units.length} rooms open. Existing floors and fit-outs stay available.</p></article>
 <div className="lodging-room-grid">{HOTEL_FLOORS.map(f=>{const open=f.floor<=l.openFloors,next=f.floor===l.openFloors+1,checks=hotelFloorChecks(b,state,f.floor);return <article className="mc-inner-panel lodging-room" key={f.floor}><div className="lodging-card-title"><h3>Floor {f.floor} · {f.name}</h3><b>{open?'Open':next?'Next expansion':'Locked'}</b></div><p>Rooms {f.floor}01–{f.floor}04 · {f.floor*4} rooms in total</p>
 {!open&&<ul className="lodging-checklist">{checks.map(c=><li key={c.label} data-ready={c.met}>{c.met?'✓':'○'} {c.label} <b>{c.value}</b></li>)}</ul>}
 <UnlockDetails visible={f.visible} milestone={open?'Already open':checks.map(c=>c.label).join(' · ')+'. Open floors in order, between weeks.'} cost={f.cost?cash(f.cost)+' · rooms include their initial linen':'Opening package included'} buildCost={f.cost} stockCost={f.cost?15:0} addedWages={f.cost?35:0} recurring="No floor fee. One optional extra housekeeper adds $35/week and a $120 hiring fee. Laundry and amenities have separate running costs." needs={f.needs+' Suggested extra opening consumables: $15, bought separately.'} next={f.unlock+'. '+(f.floor<5?'Next: '+HOTEL_FLOORS.find(next=>next.floor===f.floor+1)?.name+'.':'All 20 rooms open; improve service and rates.')}/>
 <button className={open?'mc-button':'mc-button-green'} disabled={open||!next||!!hotelFloorBlocker(b,state)||b.cash<f.cost} onClick={()=>act({type:'floor'})}>{open?'Open':next?`Open floor ${f.floor} · ${cash(f.cost)}`:'Open previous floors first'}</button></article>;})}</div></>;
}
export function HotelService({b,act}:Pick<Props,'b'|'act'>){
 const l=b.lodging!,mode=l.laundryMode??'outsourced',dirty=laundryQuantity(b),pending=laundryPending(b);
 return <article className="mc-inner-panel lodging-issue"><h3>Linen, laundry & breakfast</h3><p>Housekeeping assignment: {b.venue!.units.some(u=>u.dirty&&!u.occupied)?roomLabel({kind:'hotel'} as Property,b.venue!.units.findIndex(u=>u.dirty&&!u.occupied))+' � fresh linen, towels and cleaning products required':'All vacant rooms prepared'}. Staff walk through corridors and use the lift to reach their assigned room.</p><p>Fresh linen goes into the room, returns dirty at checkout, then goes through laundry. Worn pieces need replacement after ten uses.</p><div className="lodging-room-stats"><span>Clean linen <b>{Math.floor(b.inventory?.['stock-0']??0)}</b></span><span>Clean towels <b>{Math.floor(b.inventory?.['stock-3']??0)}</b></span><span>Dirty <b>{dirty}</b></span><span>At laundry <b>{pending}</b></span></div>
 <label>Laundry service<select aria-label="Hotel laundry service" value={mode} onChange={e=>act({type:'laundry',mode:e.target.value as 'outsourced'|'inhouse'})}><option value="outsourced">Outsourced · $4 per bag</option><option value="inhouse" disabled={!l.facilities.includes('laundry')}>In-house · requires laundry room</option></select></label>
 <p>{mode==='outsourced'?'Dirty pieces leave each morning in bags of up to 10; clean laundry returns the following morning. No laundry employee needed.':'Each morning or all-day laundry attendant washes up to 20 pieces per morning, using 1 cleaning unit per 5 pieces and $0.10 electricity per piece.'}</p>
 {(b.stockroom?.notes??[]).filter(n=>/laundry|washed|linen|worn/i.test(n)).slice(0,2).map((n,i)=><p role="status" key={i}>{n}</p>)}
 <p>{l.facilities.includes('restaurant')?`Breakfast this week: ${l.breakfastServed??0} portions served · ${l.breakfastMissed??0} missed. One refreshment portion per occupied room, 07:00–11:00; included in the room rate.`:'Breakfast unlocks with Floor 2. Install it in Upgrades when you can support its stock and running costs.'}</p><p>Installed facilities: {cash(hotelWeeklyUpkeep(b))}/week, charged as the week runs.{(l.serviceDue??0)>.01?` Unpaid facility bills: ${cash(l.serviceDue!)}; automatic retry as cash becomes available.`:''}</p></article>;
}
export function HotelExtraStaff({p,b,onChange,act}:{p:Property;b:Business;onChange:(f:(s:ExpansionState)=>ExpansionState)=>void;act:(a:LodgingAction)=>void}){
 return <>{(['concierge','laundry'] as const).map(role=>{const count=b.hires?.[role]??0,name=role==='concierge'?'Concierge':'Laundry attendant',issue=b.lodging!.issues.find(i=>!i.resolved&&i.kind!=='repair'),active=shiftActive(b,role);return <article className="mc-inner-panel lodging-staff" key={role}><div className="lodging-card-title"><h3>{name}</h3><b>{count} on team · {active?'On shift':'Off shift'}</b></div><p>{role==='concierge'?'Handles refreshments and noise complaints one at a time; maintenance workers handle repairs.':'Operates the optional laundry room. Assign morning or all-day coverage for the wash cycle.'}</p><p role="status">{!count?'No worker assigned':!b.venue!.running?'Starts work when the week opens':!active?'Off shift':role==='concierge'?(issue?`Concierge 1 → ${roomLabel(p,issue.unit)} · ${issue.kind}`:'Concierge at luggage desk · no requests waiting'):`${laundryQuantity(b)} dirty pieces · ${count*20} pieces per morning${b.lodging!.laundryMode!=='inhouse'?' · outsourced laundry currently selected':''}`}</p><label>Daily shift<select aria-label={`${name} shift`} value={b.lodging!.shifts[role]??'all'} onChange={e=>act({type:'shift',role,shift:e.target.value as StaffShift})}><option value="all">All-day rota</option><option value="morning">Morning · 06:00–14:00</option><option value="afternoon">Afternoon · 14:00–22:00</option><option value="evening">Night · 22:00–06:00</option></select></label><button className="mc-button-green" disabled={count>=8||b.cash<120||(role==='laundry'&&!b.lodging!.facilities.includes('laundry'))} onClick={()=>onChange(s=>hireBusinessStaff(s,p.id,role))}>Hire · $120 + $35/week</button></article>;})}</>;
}
