import {useEffect,useState} from 'react';
import {Business,businessSupplies,businessWages,ExpansionState,hireBusinessStaff,Property} from '../prototype/expansionModel';
import {operateVenue,serviceBlocker,VenueUnit} from './venueSimulation';
import {absoluteTime,FACILITIES,floorMilestone,lodgingClock,lodgingMetrics,LodgingAction,manageLodging,maxFloors,nextFloorCost,roomLabel,roomsPerFloor,roomTypes,shiftActive,staffCount,StaffShift} from './lodging';
import {worldTime} from './worldTime';
import './lodging.css';
const cash=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const when=(time:number)=>{const week=Math.floor(time/180)+1,c=worldTime((time%180)/1.8);return `Week ${week} · Day ${c.day} · ${c.label}`;};
type Props={p:Property;b:Business;state:ExpansionState;onChange:(f:(s:ExpansionState)=>ExpansionState)=>void;section:string;selectedUnit?:number};
function RoomCard({p,b,index,unit,act}:{p:Property;b:Business;index:number;unit:VenueUnit;act:(a:LodgingAction)=>void}){
 const[choice,setChoice]=useState(unit.type??roomTypes(p)[0].id),types=roomTypes(p),rate=unit.rate??types[0].rate,reserved=b.lodging!.bookings.find(v=>v.unit===index&&['reserved','waiting'].includes(v.status)),kind=types.find(t=>t.id===choice)!;
 const[rateDraft,setRateDraft]=useState(String(rate));useEffect(()=>setRateDraft(String(rate)),[rate]);
 const baseRate=types.find(t=>t.id===unit.type)?.rate??85,validRate=rateDraft.trim()!==''&&Number.isFinite(Number(rateDraft))&&Number(rateDraft)>=baseRate*.5&&Number(rateDraft)<=baseRate*3;
 return <article className="mc-inner-panel lodging-room"><div className="lodging-card-title"><h3>{roomLabel(p,index)}</h3><span>{unit.occupied?(p.kind==='hotel'?'Occupied':'Leased'):reserved?'Reserved':unit.dirty?'Needs cleaning':(unit.condition??100)<35?'Needs repair':'Ready'}</span></div>
  <p>{types.find(t=>t.id===unit.type)?.name} · Floor {Math.floor(index/roomsPerFloor(p))+1} · Comfort level {unit.level??1}</p>
  <label>{p.kind==='hotel'?'Nightly rate':'Weekly rent'}<input aria-label={`${roomLabel(p,index)} rate`} type="number" min={baseRate*.5} max={baseRate*3} step="5" value={rateDraft} onChange={e=>setRateDraft(e.target.value)}/></label><button className="mc-button" disabled={!validRate||Number(rateDraft)===rate} onClick={()=>act({type:'rate',unit:index,rate:Number(rateDraft)})}>Apply rate</button>{!validRate&&<p>Choose a rate from {cash(baseRate*.5)} to {cash(baseRate*3)}.</p>}
  <p>{Math.round(Math.exp(-2.5*Math.max(0,rate/(types.find(t=>t.id===unit.type)?.rate??85)-1))*100)}% price demand · {unit.occupied?`Current agreed rate: ${cash(unit.rent??rate)}`:reserved?`Reserved at ${cash(reserved.rate)}`:'Available for new bookings'}</p>
  <div className="lodging-room-stats"><span>Condition <b>{Math.round(unit.condition??100)}%</b></span><span>Cleanliness <b>{Math.round(unit.cleanliness??100)}%</b></span></div>
  <div className="lodging-actions"><button className="mc-button" disabled={(p.kind==='hotel'&&unit.occupied)||(!unit.dirty&&(unit.cleanliness??100)===100)} onClick={()=>act({type:'clean',unit:index})}>Clean · supplies</button><button className="mc-button" disabled={(unit.condition??100)>=100||b.cash<15} onClick={()=>act({type:'repair',unit:index})}>Repair · $15</button></div>
  <label>Renovation<select aria-label={`${roomLabel(p,index)} room type`} value={choice} onChange={e=>setChoice(e.target.value as typeof choice)}>{types.map(t=><option value={t.id} key={t.id}>{t.name} · {cash(t.renovation)}</option>)}</select></label>
  <button className="mc-button-blue" disabled={unit.occupied||!!reserved||b.cash<kind.renovation} onClick={()=>act({type:'renovate',unit:index,roomType:choice})}>Renovate · {cash(kind.renovation)}</button>
 </article>;
}
export function LodgingManagement({p,b,state,onChange,section,selectedUnit}:Props){
 const[filter,setFilter]=useState('all'),[floor,setFloor]=useState(selectedUnit===undefined?0:Math.floor(selectedUnit/roomsPerFloor(p))+1),[unitFilter,setUnitFilter]=useState(selectedUnit??-1);
 const l=b.lodging!,v=b.venue!,hotel=p.kind==='hotel',metrics=lodgingMetrics(b),clock=lodgingClock(b),waiting=v.visitors.filter(v=>v.state==='waiting');
 const act=(a:LodgingAction)=>onChange(s=>manageLodging(s,p.id,a));
 const notice=state.notice.startsWith(p.name+':')?<p role="status" className="lodging-notice">{state.notice}</p>:null;
 return <section className="lodging-console" aria-label={`${p.name} ${section}`}>
 {notice}
 {section==='run'&&<>
  <h3>{hotel?'Hotel operations':'Residential operations'}</h3><p>{clock.label} · {clock.period} · {hotel?'Morning checkouts and cleaning · afternoon arrivals · evening guest requests.':'Leasing, resident services and repairs. Rent is collected weekly at the agreed lease rate.'}</p>
  <div className="lodging-metrics">{[['Open floors',`${l.openFloors} / ${maxFloors(p)}`],['Occupancy',`${Math.round(metrics.occupancy)}%`],['Reputation',`${Math.round(l.reputation)} / 100`],['Waiting',waiting.length]].map(([label,value])=><div className="mc-inner-panel" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
  <div className="lodging-columns"><article className="mc-inner-panel"><h3>{hotel?'Reception queue':'Leasing appointments'}</h3>{!waiting.length&&<p>No one waiting. {v.running?'Arrivals are busiest in the afternoon.':'Start the week to open reception.'}</p>}{waiting.map(person=>{const booking=l.bookings.find(v=>v.id===person.bookingId),blocked=serviceBlocker(p,b,person.id);return <div className="lodging-list-row" key={person.id}><div><b>{booking?.name??`Walk-in ${person.id}`}</b><small>{booking?.kind??'Walk-in'} · {booking?.type??person.offerId} · {Math.ceil(person.patience)}s patience</small><small>{blocked??`Agreed rate ${cash(booking?.rate??person.agreedRate??85)}`}</small></div><button className="mc-button-green" disabled={!!blocked} onClick={()=>onChange(s=>operateVenue(s,p.id,'serve',person.id))}>{hotel?'Check in':'Sign lease'}</button></div>;})}</article>
  <article className="mc-inner-panel"><h3>{hotel?'Housekeeping & maintenance':'Resident maintenance'}</h3>{v.units.filter(u=>u.dirty||(u.condition??100)<65).length===0?<p>All rooms are ready or in good condition.</p>:v.units.map((u,i)=>u.dirty||(u.condition??100)<65?<div className="lodging-list-row" key={i}><div><b>{roomLabel(p,i)}</b><small>{u.dirty?'Cleaning needed · ':''}Condition {Math.round(u.condition??100)}%</small></div><button className="mc-button" disabled={hotel&&u.occupied&&u.dirty} onClick={()=>act({type:hotel&&u.dirty?'clean':'repair',unit:i})}>{hotel&&u.dirty?'Clean':'Repair · $15'}</button></div>:null)}</article></div>
  <h3>{hotel?'Guest requests & decisions':'Tenant requests & decisions'}</h3>{!l.issues.some(i=>!i.resolved)&&<p>No open requests. New situations appear during service.</p>}{l.issues.filter(i=>!i.resolved).map(issue=><article className="mc-inner-panel lodging-issue" key={issue.id}><b>{roomLabel(p,issue.unit)} · {issue.kind}</b><p>{issue.description} Resolve before {when(issue.deadline)}.</p><div className="lodging-actions"><button className="mc-button-green" onClick={()=>act({type:'issue',id:issue.id,choice:'help'})}>Help · {cash(issue.kind==='repair'?15:issue.kind==='noise'?5:3)}</button><button className="mc-button" onClick={()=>act({type:'issue',id:issue.id,choice:'refund'})}>Refund 25% of agreed rate</button><button className="mc-button" onClick={()=>act({type:'issue',id:issue.id,choice:'move'})}>Move to a ready unit</button></div></article>)}
  {l.lastReport&&<article className="mc-inner-panel lodging-issue"><h3>Week {l.lastReport.week} performance</h3><p>{l.lastReport.served} served · {l.lastReport.lost} lost · {Math.round(l.lastReport.occupancy)}% occupancy · {cash(l.lastReport.averageRate)} average rate · {cash(l.lastReport.revenue)} income</p><p>Next expansion: {l.openFloors<maxFloors(p)?`${floorMilestone(b)} total guests / tenants served and ${cash(nextFloorCost(p,b))} for floor ${l.openFloors+1}.`:'All floors are open. Improve rooms and facilities next.'}</p></article>}
 </>}
 {section==='prices'&&<><h3>{hotel?'Rooms & nightly rates':'Homes & weekly rents'}</h3><p>Each unit has its own rate, condition and room type. Booked prices and signed leases remain unchanged when you edit rates.</p><label>View floor<select aria-label="Rooms floor filter" value={floor} onChange={e=>{setFloor(Number(e.target.value));setUnitFilter(-1);}}><option value={0}>All open floors</option>{Array.from({length:l.openFloors},(_,i)=><option key={i} value={i+1}>Floor {i+1}</option>)}</select></label><label>View unit<select aria-label="Room selection" value={unitFilter} onChange={e=>setUnitFilter(Number(e.target.value))}><option value={-1}>All units on this floor</option>{v.units.map((u,i)=>(!floor||Math.floor(i/roomsPerFloor(p))+1===floor)&&<option key={i} value={i}>{roomLabel(p,i)}</option>)}</select></label><div className="lodging-room-grid">{v.units.map((u,i)=>(unitFilter<0||unitFilter===i)&&(!floor||Math.floor(i/roomsPerFloor(p))+1===floor)&&<RoomCard key={i} index={i} unit={u} p={p} b={b} act={act}/>)}</div></>}
 {section==='bookings'&&<><h3>{hotel?'Bookings & guest stays':'Applications & leases'}</h3><p>{hotel?'Reservations hold a room and an agreed nightly price. Family stays last two nights; group reservations receive a 10% discount.':'Applicants sign six-week leases. Current tenants keep their agreed weekly rent until the lease ends.'}</p><label>Show<select aria-label="Booking status" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','reserved','waiting','staying','completed','cancelled'].map(s=><option value={s} key={s}>{s}</option>)}</select></label>{!l.bookings.length&&<p>No bookings yet. Open for a week to receive enquiries and walk-ins.</p>}{[...l.bookings].reverse().filter(v=>filter==='all'||v.status===filter).map(booking=><article className="mc-inner-panel lodging-booking" key={booking.id}><div className="lodging-card-title"><h3>{booking.name}</h3><b>{booking.status}</b></div><p>{booking.kind} · {booking.type} · {cash(booking.rate)} / {hotel?'night':'week'}{hotel?` · ${booking.nights} night(s)`:''}{booking.unit!==undefined?` · ${roomLabel(p,booking.unit)}`:''}</p><p>Arrival {when(booking.arrival)}{booking.departure?` · ${hotel?'Checkout':'Lease ends'} ${when(booking.departure)}`:''}</p>{booking.review!==undefined&&<p>Review {booking.review.toFixed(1)} / 5</p>}{['reserved','waiting'].includes(booking.status)&&<div className="lodging-actions">{booking.status==='waiting'&&<button className="mc-button-green" disabled={!!serviceBlocker(p,b,v.visitors.find(v=>v.bookingId===booking.id)?.id)} onClick={()=>onChange(s=>operateVenue(s,p.id,'serve',v.visitors.find(v=>v.bookingId===booking.id)?.id))}>{hotel?'Check in':'Sign lease'}</button>}<button className="mc-button" onClick={()=>act({type:'cancel',id:booking.id})}>Decline / cancel · reputation −1</button></div>}</article>)}</>}
 {section==='staff'&&<><h3>{hotel?'Hotel team & shifts':'Property team & shifts'}</h3><p>One {hotel?'receptionist and housekeeper':'leasing assistant and caretaker'} is included in the base {cash(p.wages)} weekly wages. Each additional worker costs $35 per week; managers cost $60. Wages are paid after Day 3 of the following week.</p>{['service','care','maintenance'].map(role=>{const count=staffCount(p,b,role),name=role==='service'?(hotel?'Receptionist':'Leasing assistant'):role==='care'?(hotel?'Housekeeper':'Caretaker'):'Maintenance worker',work=role==='service'?waiting.length:role==='care'?v.units.filter(u=>u.dirty).length:v.units.filter(u=>(u.condition??100)<65).length;return <article className="mc-inner-panel lodging-staff" key={role}><div className="lodging-card-title"><h3>{name}</h3><b>{count} on team · {shiftActive(b,role)?'On shift':'Off shift'}</b></div><p>{work} tasks waiting · {role==='service'?'Checks in one guest or tenant at a time.':role==='care'?'Cleans or services one unit at a time using stock.':'Repairs faults using repair stock and $15 per job.'}</p><label>Daily shift<select aria-label={`${name} shift`} value={l.shifts[role]??'all'} onChange={e=>act({type:'shift',role,shift:e.target.value as StaffShift})}><option value="all">All-day rota</option><option value="morning">Morning · 06:00–14:00</option><option value="afternoon">Afternoon · 14:00–22:00</option><option value="evening">Night · 22:00–06:00</option></select></label><button className="mc-button-green" disabled={(b.hires?.[role]??0)>=8||b.cash<120} onClick={()=>onChange(s=>hireBusinessStaff(s,p.id,role as 'service'|'care'|'maintenance'))}>Hire · $120</button></article>;})}<article className="mc-inner-panel lodging-staff"><h3>Purchasing manager</h3><p>Orders only this building’s supplies, respecting minimum stock targets, weekly budget and cash reserve. Set these in Inventory.</p><button className="mc-button-green" disabled={!!b.manager||b.cash<250} onClick={()=>onChange(s=>hireBusinessStaff(s,p.id,'manager'))}>{b.manager?'Hired':'Hire · $250'}</button></article><p><b>Total wages: {cash(businessWages(p,b))} / week</b></p></>}
 {section==='upgrades'&&<><h3>Open floors & improve the building</h3><p>Reception is on the ground floor. Start with one {hotel?'guest':'residential'} floor, then open floors in order between weeks. All costs come from this building’s account.</p><div className="lodging-metrics"><div className="mc-inner-panel"><span>Floors open</span><strong>{l.openFloors} / {maxFloors(p)}</strong></div><div className="mc-inner-panel"><span>Total served</span><strong>{v.totalServed}</strong></div></div><div className="lodging-room-grid">{Array.from({length:maxFloors(p)},(_,i)=>{const n=i+1,open=n<=l.openFloors,next=n===l.openFloors+1;return <article className="mc-inner-panel lodging-room" key={n}><h3>Floor {n}</h3><p>{roomsPerFloor(p)} {hotel?'guest rooms':'homes'} · {open?'Open':next?`Requires ${floorMilestone(b)} guests / tenants served`:'Open the previous floor first'}</p><button className={open?'mc-button':'mc-button-green'} disabled={open||!next||v.running||v.totalServed<floorMilestone(b)||b.cash<nextFloorCost(p,b)} onClick={()=>act({type:'floor'})}>{open?'Open':next?`Open floor · ${cash(nextFloorCost(p,b))}`:'Locked'}</button></article>;})}</div><h3>Facilities</h3><div className="lodging-room-grid">{FACILITIES.filter(f=>hotel||f.id!=='restaurant').map(f=><article className="mc-inner-panel lodging-room" key={f.id}><h3>{f.name}</h3><p>{f.description}</p><p>Requires {f.floor} open floors.</p><button className="mc-button-green" disabled={l.facilities.includes(f.id)||l.openFloors<f.floor||v.running||b.cash<f.cost} onClick={()=>act({type:'facility',id:f.id})}>{l.facilities.includes(f.id)?'Installed':`Install · ${cash(f.cost)}`}</button></article>)}</div></>}
 </section>;
}
