import {MallOperationsDepth,MallReadiness,MallContractSettings,MallTenantDetails} from './MallDepthManagement';
import {mallFloorChecks} from './mallDepth';
import {useEffect,useState} from 'react';
import type {Business,ExpansionState,Property} from '../prototype/expansionModel';
import type {ManagementTab} from '../prototype/BusinessManagement';
import type {VenueUnit} from './venueSimulation';
import {UnlockDetails} from '../components/UnlockDetails';
import '../components/restaurantProgression.css';
import {SHOP_TYPES,PLAZA_FLOORS,SHOPS_PER_FLOOR,MALL_FLOORS,MALL_FACILITIES,mallWeeklyUpkeep,mallAppeal,shopType,plazaUnitName,managePlaza,plazaLeaseBlocker,plazaCareBlocker,plazaFloorCost,plazaFloorMilestone} from './plaza';
import type {PlazaAction,ShopType} from './plaza';
import './lodging.css';
import './mall.css';
const cash=(v:number)=>v.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function ShopCard({p,b,u,index,act}:{p:Property;b:Business;u:VenueUnit;index:number;act:(a:PlazaAction)=>void}){
 const type=shopType(u.shopType),[rate,setRate]=useState(String(u.rate??type.rent)),[fitout,setFitout]=useState(type.id);
 useEffect(()=>setRate(String(u.rate??type.rent)),[u.rate,type.rent]);useEffect(()=>setFitout(type.id),[type.id]);
 const chosen=shopType(fitout),valid=rate.trim()!==''&&Number.isFinite(Number(rate))&&Number(rate)>=type.rent*.5&&Number(rate)<=type.rent*3;
 return <article className="mc-inner-panel lodging-room"><div className="lodging-card-title"><h3>{plazaUnitName(index)} · {type.name}</h3><span>{u.occupied?'Leased':u.dirty?'Needs cleaning':(u.condition??100)<65?'Needs repairs':'Available'}</span></div>
  <p>{index<4?'Ground floor':`Floor ${Math.floor(index/4)}`} · {MALL_FLOORS[Math.floor(index/4)].name} · {u.occupied?`${u.tenantName} · ${cash(u.rent??0)} / week · lease ends Week ${u.leaseEnd}`:'Advertised to prospective tenants during the week.'}</p>
  <div className="lodging-room-stats"><span>Condition {Math.round(u.condition??100)}%</span><span>Cleanliness {Math.round(u.cleanliness??100)}%</span></div>
  <label>Asking rent / week<input aria-label={`${plazaUnitName(index)} asking rent`} type="number" min={type.rent*.5} max={type.rent*3} step={5} value={rate} onChange={e=>setRate(e.target.value)}/></label><button className="mc-button" disabled={!valid||Number(rate)===u.rate} onClick={()=>act({type:'rate',unit:index,rate:Number(rate)})}>Apply asking rent</button>
  <p>{Math.round(Math.exp(-2.3*Math.max(0,(u.rate??type.rent)/type.rent-1))*100)}% enquiry demand at this rent. Existing tenants keep their signed rate.</p>
  <label>Shop fit-out<select aria-label={`${plazaUnitName(index)} shop type`} value={fitout} disabled={u.occupied} onChange={e=>setFitout(e.target.value as ShopType)}>{SHOP_TYPES.map(t=><option key={t.id} value={t.id}>{t.name} · {cash(t.fitout)}</option>)}</select></label>
  <button className="mc-button-green" disabled={u.occupied||fitout===type.id||b.cash<chosen.fitout} onClick={()=>act({type:'fitout',unit:index,shop:fitout})}>{fitout===type.id?'Current fit-out':`Refit shop · ${cash(chosen.fitout)}`}</button>
  <div className="lodging-actions"><button className="mc-button" disabled={!!plazaCareBlocker(p,b,index)} onClick={()=>act({type:'clean',unit:index})}>Clean · supplies</button><button className="mc-button" disabled={!!plazaCareBlocker(p,b,index,true)} onClick={()=>act({type:'repair',unit:index})}>Repair · $15</button></div>
  {(u.dirty||(u.condition??100)<65)&&<p>{plazaCareBlocker(p,b,index,(u.condition??100)<65)??'The caretaker will service this shop during the week.'}</p>}
 </article>;
}
export function PlazaManagement({p,b,state,section,selectedUnit,onChange}:{p:Property;b:Business;state:ExpansionState;section:ManagementTab;selectedUnit?:number;onChange:(f:(s:ExpansionState)=>ExpansionState)=>void}){
 const plaza=b.plaza!,venue=b.venue!,[floor,setFloor]=useState(-1),[unitFilter,setUnitFilter]=useState(selectedUnit??-1),act=(a:PlazaAction)=>onChange(s=>managePlaza(s,p.id,a));
 const occupied=venue.units.filter(u=>u.occupied),rent=occupied.reduce((n,u)=>n+(u.rent??0),0);
 return <section className="lodging-console mall-console" aria-label="Shopping mall management"><p className="lodging-notice" role="status">{state.notice}</p>
  {(section==='run'||section==='bookings')&&<><h3>{section==='run'?'Shopping mall operations':'Tenants & leases'}</h3><p>Build a place to shop, eat and spend the day. Choose your tenant mix, set weekly rents and expand the mall. Shopkeepers run their own sales and stock; your account receives shop rent and pays for shared staff, supplies and facilities. Willow Gardens remains a public park.</p>
   <div className="lodging-metrics">{[['Leased shops',`${occupied.length} / ${venue.units.length}`],['Agreed weekly rent',cash(rent)],['Open floors',`${plaza.openFloors} / ${PLAZA_FLOORS}`],['Visitor footfall',Math.floor(plaza.footfall)]].map(([label,value])=><div className="mc-inner-panel" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
   {section==='run'&&b.plaza?.depth&&<MallOperationsDepth p={p} b={b} state={state} onChange={onChange}/>}
   {b.plaza?.depth&&<MallContractSettings p={p} b={b} onChange={onChange}/>}
   <label><span>Leasing assistant: automatically sign suitable applicants</span><input type="checkbox" aria-label="Automatically sign shop leases" checked={plaza.autoLease} onChange={e=>act({type:'auto',enabled:e.target.checked})}/></label>
   <h3>Shop applications · {plaza.applications.length}</h3><p>Choose 8-, 16- or 24-week fixed-rent terms. First week is paid when you sign; later rent arrives at the start of each week. Higher asking rents reduce enquiries.</p>
   {!plaza.applications.length&&<p>{occupied.length===venue.units.length?(plaza.openFloors<PLAZA_FLOORS?'All open shops are leased. Expand to make room for more tenants.':'All twenty shops are leased. Keep the mall maintained and review rents before leases renew.'):venue.running?'Waiting for shopkeepers to enquire.':'Start the week to receive applications for vacant shops.'}</p>}
   {plaza.applications.map(a=><article className="mc-inner-panel lodging-booking" key={a.id}><div className="lodging-card-title"><h3>{a.name}</h3><b>{cash(a.rate)} / week</b></div><p>{plazaUnitName(a.unit)} · {a.term??8}-week lease · offer expires in {Math.max(0,Math.ceil(a.expiresAt-((state.week-1)*180+venue.clock)))}s</p><div className="lodging-actions"><button className="mc-button-green" disabled={!!plazaLeaseBlocker(b,a,state.week)} onClick={()=>act({type:'accept',id:a.id})}>Accept tenant · {cash(a.rate)}</button><button className="mc-button" onClick={()=>act({type:'decline',id:a.id})}>Decline</button></div>{plazaLeaseBlocker(b,a,state.week)&&<p>{plazaLeaseBlocker(b,a,state.week)}</p>}</article>)}
   <h3>Current tenants</h3>{!occupied.length&&<p>No leases signed yet. Fit out a vacant unit and accept an application.</p>}{venue.units.map((u,i)=>u.occupied&&<article key={i} className="mc-inner-panel lodging-booking"><b>{plazaUnitName(i)} · {u.tenantName}</b><p>{cash(u.rent??0)} / week · rent recorded for Week {u.rentWeek} · expires at the start of Week {u.leaseEnd}. {u.dirty||(u.condition??100)<65?'Needs upkeep.':'Shop ready for trading.'}</p>{b.plaza?.depth&&<MallTenantDetails p={p} b={b} state={state} onChange={onChange} index={i}/>}</article>)}
  </>}
  {section==='prices'&&<><h3>Shop units & weekly rents</h3><p>Choose from {SHOP_TYPES.length} shop types, including cafés, restaurants, toys, fashion, electronics and groceries. Refitting changes the interior; occupied shops keep their type until their lease ends.</p><label>Floor<select aria-label="Mall floor filter" value={floor} onChange={e=>{setFloor(Number(e.target.value));setUnitFilter(-1);}}><option value={-1}>All open floors</option>{Array.from({length:plaza.openFloors},(_,i)=><option key={i} value={i}>{i===0?'G':i} · {MALL_FLOORS[i].name}</option>)}</select></label><label>Shop<select aria-label="Mall shop filter" value={unitFilter} onChange={e=>setUnitFilter(Number(e.target.value))}><option value={-1}>All shops</option>{venue.units.map((_,i)=><option value={i} key={i}>{plazaUnitName(i)}</option>)}</select></label><div className="lodging-room-grid">{venue.units.map((u,i)=>(floor<0||Math.floor(i/4)===floor)&&(unitFilter<0||unitFilter===i)&&<ShopCard key={i} p={p} b={b} u={u} index={i} act={act}/>)}</div></>}
  {section==='upgrades'&&<><h3>Build your shopping destination</h3><p>Start with the ground floor. Grow to five floors and twenty shops, with a different destination on every level. Open floors in order between weeks; each construction is paid only once. Your existing shops and leases stay intact.</p><MallReadiness p={p} b={b} state={state}/><div className="mall-floor-plan">{MALL_FLOORS.map((definition,i)=>{const open=i<plaza.openFloors,next=i===plaza.openFloors;return <article className={`mc-inner-panel mall-floor-card ${open?'is-open':''}`} key={i}><div className="mall-level-number">{i===0?'G':i}</div><div><h3>{definition.name}</h3><p>{definition.description}</p><small>{SHOPS_PER_FLOOR} shops · {definition.shops.map(id=>shopType(id).name).join(' / ')}</small><p>{open?'Floor open':next?`${plaza.leasesSigned} / ${plazaFloorMilestone(b)} leases signed · +$18 weekly shared-space upkeep`:'Open the floor below first'}</p></div><UnlockDetails upkeep={i===0?0:18} visible={definition.description+" Four new tenant shopfronts."} stockCost={35} addedWages={35} milestone={i===0?"Opening floor":(i*4)+" cumulative signed leases, plus occupancy/service readiness shown above; build between weeks."} cost={i===0?"Opening package":cash(4000+i*2500)} recurring="+$18 weekly shared-space upkeep per additional floor. Existing lease payments continue." needs="Cleaning, paper goods, light bulbs, repair and safety stock; food-court tray supplies and team coverage. Tenants buy their own resale stock." next={i<4?"Next: "+MALL_FLOORS[i+1].name:"All floors open. Improve tenant mix and visitor facilities."}/><button className="mc-button-green" disabled={open||!next||venue.running||mallFloorChecks(p,b,state).some(c=>!c.met)||b.cash<plazaFloorCost(b)} onClick={()=>act({type:'floor',floor:i+1})}>{open?'Open':next?`Open floor · ${cash(plazaFloorCost(b))}`:'Locked'}</button></article>;})}</div>
   <h3>Visitor facilities</h3><p>Add facilities after opening their floor. Each facility has a visible interior, attracts more visitors and has its own weekly operating cost.</p><div className="lodging-room-grid">{MALL_FACILITIES.map(f=>{const built=plaza.facilities.includes(f.id),locked=f.floor>=plaza.openFloors;return <article className="mc-inner-panel lodging-room" key={f.id}><div className="lodging-card-title"><h3>{f.name}</h3><span>Floor {f.floor}</span></div><p>{f.description}</p><div className="lodging-room-stats"><span>+{Math.round(f.appeal*100)}% attraction</span><span>{cash(f.weekly)}/week upkeep</span></div><UnlockDetails upkeep={f.weekly} visible={f.description} milestone={"Open floor "+f.floor+" and finish the week before building."} cost={cash(f.cost)} recurring={cash(f.weekly)+" / week, utilities and facility service; hired staff wages separate."} needs="Cleaning, paper goods, repair and safety supplies. Play requires an attendant; cinema requires an operator. Hired staff wages are separate from upkeep." next="Watch footfall and tenant occupancy; add the next facility when its floor opens."/><button className="mc-button-green" disabled={built||locked||venue.running||b.cash<f.cost} onClick={()=>act({type:'facility',facility:f.id})}>{built?'Facility open':locked?`Unlock floor ${f.floor} first`:`Build · ${cash(f.cost)}`}</button></article>;})}</div>{venue.running&&<p>Finish the current week before building floors or facilities.</p>}</>}
 </section>;
}

