import {BUILDING_DESIGNS,BUSINESS_NAME_LIMIT,cleanBusinessName,designDescription,type BuildingDesignId} from './buildingDesigns';
import {BuildingDesignPreview} from './BuildingDesignPreview';
import {useEffect,useState,useRef} from 'react';
import type {GameState} from '../hooks/useGameLoop';
import {acquire,PROPERTIES,propertyById,type ExpansionState} from '../prototype/expansionModel';
import {expansionFunding} from './expansionFunding';
import {LAND_PLOTS,siteOffer,offerLabel,listedPropertyIdentity,landPlotById,acquisitionQuote,builtPropertyId,canLease,constructionIdentity,marketKindName,propertyLevel} from './propertyMarket';
import {RestaurantTypePicker} from '../components/RestaurantTypePicker';
import {defaultRestaurantType} from '../restaurantTypes';
import {useDialogFocus} from '../ui/dialogFocus';
import './propertyMarket.css';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export function PropertyMarket({state,restaurants,onChange,onEnter,onClose,onLocate,initialId}:{state:ExpansionState;restaurants:Record<string,GameState>;onChange:(f:(s:ExpansionState)=>ExpansionState)=>void;onEnter:(id:string)=>void;onClose:()=>void;onLocate?:(id:string)=>void;initialId?:string}){
 const first=Object.keys(state.businesses).length===0;
 const openingSelection=initialId??(first?'diner':PROPERTIES.find(p=>!state.businesses[p.id]&&propertyLevel(p.kind)<=state.market!.level)?.id??('plot-'+LAND_PLOTS.find(p=>!state.market!.parcels[p.id])?.id));
 const [selection,setSelection]=useState(openingSelection),[tenure,setTenure]=useState<'owned'|'leased'>(openingSelection==='diner'?'leased':'owned');
 const [type,setType]=useState(defaultRestaurantType(openingSelection)),[source,setSource]=useState(Object.keys(state.businesses)[0]??''),[term,setTerm]=useState<10|20|40>(40),[pending,setPending]=useState<string|null>(null);
 const [businessName,setBusinessName]=useState(''),[design,setDesign]=useState<BuildingDesignId>('heritage');
 const [search,setSearch]=useState(''),[area,setArea]=useState('All areas'),[limit,setLimit]=useState(12),[offerFilter,setOfferFilter]=useState('all');
 const dialog=useDialogFocus<HTMLElement>(onClose),market=state.market!,articleRef=useRef<HTMLElement>(null);
 useEffect(()=>{articleRef.current?.scrollTo({top:0});},[selection]);
 const selectedPlot=selection.startsWith('plot-')?landPlotById(selection.slice(5)):undefined;
 const selectedOffer=selectedPlot?siteOffer(selectedPlot,market.listingSeed):null;
 const resolved=selectedPlot?(selectedOffer!.mode==='land'?builtPropertyId(selectedPlot.id,selectedPlot.kinds[0]):selectedOffer!.id):selection;
 const id=propertyById(resolved)?resolved:'diner';
 const p=propertyById(id)!,built=constructionIdentity(id),listing=listedPropertyIdentity(id),food=['restaurant','cafe'].includes(p.kind),method=built?'construction':listing?listing.mode:canLease(p.kind)&&tenure==='leased'?'lease':'purchase',quote=acquisitionQuote(p,method);
 const funding=state.businesses[source]?source:Object.keys(state.businesses)[0]??'',cash=first?market.ownerCash:state.businesses[funding]?.cash??0,total=quote.cost+(first?0:quote.workingCash),locked=market.level<quote.level;
 const funds=expansionFunding(state,funding,restaurants[funding]),available=first?cash:funds.available;
 const planning=Object.values(restaurants).every(r=>r.phase==='planning')&&!Object.values(state.businesses).some(b=>b.venue?.running);
 const owned=!!state.businesses[id]||!!((built??listing)&&market.parcels[(built??listing)!.plot.id]);
 useEffect(()=>{if(pending&&state.businesses[pending]){onEnter(pending);setPending(null);onClose();}},[pending,state.businesses]);
 const choose=(next:string,lease=false)=>{setSelection(next);setTenure(lease?'leased':'owned');setType(defaultRestaurantType(next));setBusinessName('');setDesign('heritage');};
 const availablePlots=LAND_PLOTS.filter(plot=>!market.parcels[plot.id]),shownPlots=availablePlots.filter(plot=>(area==='All areas'||area===plot.area)&&(offerFilter==='all'||siteOffer(plot,market.listingSeed).mode===offerFilter)&&plot.name.toLowerCase().includes(search.trim().toLowerCase()));
 return <div className="property-market-backdrop"><section ref={dialog.ref} tabIndex={-1} onKeyDown={dialog.onKeyDown} className="mc-panel property-market" role="dialog" aria-modal="true" aria-label="Property market">
  <header><div><small>BITE TYCOON MANAGEMENT CONSOLE · PLAYER LEVEL {market.level}</small><h1>{first?'Choose your first business':'Property market'}</h1><p>{first?'Your starting investment: '+money(market.ownerCash):'Each property has its own cash, staff and stockroom.'}</p></div><button className="mc-button" onClick={onClose}>{first?'Browse map':'Close'}</button></header>
  <div className="market-body"><nav aria-label="Available properties">
   <h2>{first?'1. Choose your route':'Find your next business'}</h2>
   {first&&<><button className="mc-button market-choice" aria-pressed={id==='diner'&&method==='lease'} onClick={()=>choose('diner',true)}><strong>Lease an empty shop</strong><span>Lower opening cost · fit out a restaurant · monthly rent</span></button><button className="mc-button market-choice" aria-pressed={id==='shop'&&method==='purchase'} onClick={()=>choose('shop')}><strong>Buy an operating supermarket</strong><span>Own the land & building · fitted, stocked and staffed</span></button><button className="mc-button market-choice" aria-pressed={built?.plot.id==='commercial'} onClick={()=>choose('plot-commercial')}><strong>Buy land & build</strong><span>Choose your business, design & name · complete opening package</span></button><p className="market-site-help">Pick one, review the full cost, then enter your business and start the week.</p></>}
   <details className="market-all-sites" open={!first||!!initialId}><summary>Browse all commercial offers</summary>
   {PROPERTIES.filter(p=>!state.businesses[p.id]).map(item=><button key={item.id} className="mc-button market-choice" aria-pressed={id===item.id} onClick={()=>choose(item.id,item.id==='diner')}><strong>{item.id==='diner'?'Market Street restaurant':item.name}</strong><span>{propertyLevel(item.kind)>market.level?'Locked · Player Level '+propertyLevel(item.kind):item.id==='diner'?'For lease · '+money(acquisitionQuote(item,'lease').cost):'For sale · '+money(acquisitionQuote(item,'purchase').cost)}</span></button>)}
   <h2>Commercial sites · {availablePlots.length} available</h2>
   <p className="market-site-help">Blue signs: empty shops for lease. Gold: operating businesses for sale. Green: land to build or redevelop. Offers stay the same when you reload.</p>
   <label className="market-label">Offer type<select aria-label="Offer type" value={offerFilter} onChange={e=>{setOfferFilter(e.target.value);setLimit(12);}}><option value="all">All offers</option><option value="lease">Empty shops for lease</option><option value="purchase">Operating businesses for sale</option><option value="land">Land & redevelopment</option></select></label>
   <label className="market-label">Find a site<input type="search" aria-label="Search commercial sites" placeholder="Address or avenue" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12);}}/></label>
   <label className="market-label">Area<select aria-label="Commercial area" value={area} onChange={e=>{setArea(e.target.value);setLimit(12);}}>{['All areas','Town centre','North Market','East Market','South Market'].map(a=><option key={a}>{a}</option>)}</select></label>
   <p className="market-site-help">{shownPlots.length} matching sites · land is included in every build quote.</p>
   {shownPlots.slice(0,limit).map(plot=><button key={plot.id} className="mc-button market-choice" aria-pressed={(built??listing)?.plot.id===plot.id} onClick={()=>choose('plot-'+plot.id)}><strong>{plot.name}</strong><span>{plot.area} · {offerLabel(siteOffer(plot,market.listingSeed).mode)}</span></button>)}
   {!shownPlots.length&&<p>No sites match this search.</p>}
   {shownPlots.length>limit&&<button className="mc-button" onClick={()=>setLimit(n=>n+24)}>Show more sites</button>}
   </details><div className="market-level-help"><strong>How player levels work</strong><p>Your highest earned business level unlocks new property types. Buying property does not raise your level.</p><p>Level 1: restaurants & supermarkets<br/>Level 3: hotels<br/>Level 4: apartments<br/>Level 5: shopping malls</p><p>Grow through service milestones and paid upgrades. For example, a restaurant needs 60 guests for Level 2 and 180 guests plus an 80% service result for Level 3. See each business’s Upgrades panel for every requirement.</p></div>
  </nav><article ref={articleRef}>
   <small>{first?'2. Review your opening plan':'Opening plan'}</small><h2>{built?'Build on '+built.plot.name:p.id==='diner'?'Market Street restaurant':p.name}</h2>
   {built&&<><p>{built.plot.description}</p><div className="market-location"><span>{built.plot.area} · map {built.plot.position[0]}, {built.plot.position[2]}</span>{onLocate&&<button className="mc-button" onClick={()=>onLocate('plot-'+built.plot.id)}>Locate on map</button>}</div><label className="market-label">What would you like to build?<select aria-label="Building type" value={id} onChange={e=>{setSelection(e.target.value);setType(defaultRestaurantType(e.target.value));}}>{built.plot.kinds.map(kind=><option key={kind} value={builtPropertyId(built.plot.id,kind)}>{marketKindName(kind)} · Player Level {propertyLevel(kind)}</option>)}</select></label><p className="market-site-help">Restaurant & supermarket: Level 1 · Hotel: Level 3 · Apartments: Level 4 · Mall: Level 5. {built.plot.id!=='large'&&<>Malls need the larger Park Avenue plot. <button className="mc-button" onClick={()=>choose('built-large-plaza')}>View mall site</button></>}</p></>}
   <label className="market-label">Business name<input aria-label="Business name" maxLength={BUSINESS_NAME_LIMIT} value={businessName} placeholder={p.name} onChange={e=>setBusinessName(e.target.value)} aria-describedby="market-name-help"/></label>
   <p id="market-name-help" className="market-site-help">Your name appears on the building, map and business accounts. Leave blank to keep the suggested name.</p>
   {built&&<section className="market-designs" aria-label="Building design"><h3>Choose your building design</h3><div className="market-design-choices">{BUILDING_DESIGNS.map(d=><button key={d.id} className={design===d.id?"mc-button-selected":"mc-button"} aria-pressed={design===d.id} onClick={()=>setDesign(d.id)}><span className="market-design-swatch" style={{background:d.wall,borderColor:d.frame}}/><b>{d.name}</b><small>Included in build price</small></button>)}</div><p>{designDescription(p.kind,design)}</p><BuildingDesignPreview property={{...p,design,name:cleanBusinessName(businessName)??p.name}} identity={type}/><p className="market-site-help">Preview shows your starting building. {p.kind==='hotel'||p.kind==='apartments'?'Ground reception + Floor 1.':p.kind==='plaza'?'Ground-floor concourse and four shops.':'Your initial trading floor.'} Later floors require service milestones and a paid build. All designs have the same capacity and included equipment.</p></section>}
   <div className="market-at-glance"><div><small>OPENING PAYMENT</small><strong>{money(total)}</strong></div><div><small>{first?'CASH LEFT TO OPERATE':'LENDER CASH LEFT'}</small><strong>{money(cash-total)}</strong></div><div><small>{method==='lease'?'MONTHLY RENT':'OWNERSHIP'}</small><strong>{method==='lease'?money(quote.monthlyRent):'Land + building'}</strong></div></div>
   <p className="market-offer-type">{method==='lease'?'EMPTY PREMISES · LEASE & FIT OUT':method==='purchase'?'OPERATING BUSINESS · LAND & BUILDING INCLUDED':'SERVICED LAND · BUILD A NEW BUSINESS'}</p>
   {method==='lease'&&<p>You are renting an empty unit. The opening payment below covers lease entry, furniture, equipment and initial stock. Your chosen business opens only after this setup is paid. You do not own the land or building.</p>}
   {method==='purchase'&&<p>Take over the equipped premises, opening team and stock, together with the land and building. Your sales and profit history start at handover; the previous owner’s cash and debts do not transfer. All businesses begin at Level 1 under your management.</p>}
   {listing&&onLocate&&<button className="mc-button" onClick={()=>onLocate('plot-'+listing.plot.id)}>Locate this offer on map</button>}
   {p.kind==='plaza'&&<p>Malls cannot be leased. Buy an existing mall or build on the large plot, then earn and pay for upper-floor upgrades.</p>}
   {!built&&!listing&&canLease(p.kind)&&<div className="market-tenure"><button className="mc-button" aria-pressed={method==='lease'} onClick={()=>setTenure('leased')}>Lease · {money(acquisitionQuote(p,'lease').cost)}</button><button className="mc-button" aria-pressed={method==='purchase'} onClick={()=>setTenure('owned')}>Buy · {money(acquisitionQuote(p,'purchase').cost)}</button></div>}
   {food&&<RestaurantTypePicker value={type} onChange={setType} id="market-restaurant-type"/>}
   <div className="mc-panel market-package"><strong>{method==='lease'?'Included in your fit-out':'Included at handover'} · Business Level 1</strong><p>{food?'Dining room, tables, chairs, equipped kitchen, chef, waiter and ingredients for your selected type.':p.kind==='shop'?'Grocery displays, checkout, receiving area, cashier, stock assistant and initial produce, bread, milk and pantry stock.':p.kind==='hotel'?'Ground-floor reception and lounge, plus Floor 1 with four furnished standard guest rooms, bathrooms, linen, supplies and the opening team.':p.kind==='apartments'?'Ground-floor reception, plus Floor 1 with three studio homes, essential furnishings, maintenance supplies and the opening team.':'Ground-floor shopping concourse with four ready-to-let shops, shared facilities, opening supplies and the building team. Tenant applications arrive when you start the week.'}</p>
   {['hotel','apartments'].includes(p.kind)&&<p><b>Upper floors are not included.</b> Meet each floor’s service requirements, then pay its build cost in Upgrades. {p.kind==='hotel'?'Five guest floors':'Ten residential floors'} maximum, plus ground-floor reception. Your player level never opens these floors for free.</p>}
   <p>Furniture, equipment and starting stock are included in this quote. Ongoing wages, restocking and later upgrades are paid by this business.</p></div>
   {!first&&<><label className="market-label">Lending business<select aria-label="Acquisition funding business" value={funding} onChange={e=>setSource(e.target.value)}>{Object.keys(state.businesses).map(key=><option key={key} value={key}>{propertyById(key,state.businesses[key])!.name} · {money(state.businesses[key].cash)}</option>)}</select></label><label className="market-label">Property loan term<select aria-label="Property loan term" value={term} onChange={e=>setTerm(Number(e.target.value) as typeof term)}>{[10,20,40].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></label></>}
   <dl className="market-quote">{built&&<><dt>Land (included)</dt><dd>{money(quote.land)}</dd><dt>Building, fit-out & starter stock (included)</dt><dd>{money(quote.building)}</dd></>}{method==='purchase'&&<><dt>Land ownership (included)</dt><dd>{money(quote.land)}</dd><dt>Building, equipment & stock (included)</dt><dd>{money(quote.building)}</dd></>}{method==='lease'&&<><dt>Lease entry & premises preparation</dt><dd>{money(quote.leaseEntry)}</dd><dt>{food?'Tables, chairs, kitchen & initial ingredients':'Shelves, checkout, chillers & initial stock'}</dt><dd>{money(quote.fitOut)}</dd></>}<dt><b>{built?'Total build cost':method==='lease'?'Lease opening package':'Purchase opening package'}</b></dt><dd><b>{money(quote.cost)}</b></dd>{!first&&<><dt>Opening cash retained in new account</dt><dd>{money(quote.workingCash)}</dd><dt>Total repayable property loan</dt><dd>{money(total)}</dd><dt>Automatic loan payment / week</dt><dd>{money(Math.ceil(total/term*100)/100)}</dd></>}<dt>{first?'Cash left in your new business':'Lender’s cash after funding'}</dt><dd className={cash<total?'text-red-700':'text-green-700'}>{money(cash-total)}</dd>{!first&&<><dt>Lender’s protected bills, wages, stock & buffer</dt><dd>{money(funds.reserve)}</dd><dt>Lender’s free cash after funding</dt><dd className={available<total?'text-red-700':'text-green-700'}>{money(available-total)}</dd></>}<dt>Opening team wages / week</dt><dd>{money(food?59:p.wages)}</dd><dt>Property rent</dt><dd>{method==='lease'?money(quote.monthlyRent)+' / month':'None · owned building'}</dd></dl>
   {method==='lease'&&<p>One game month is four weeks. Rent is recorded weekly and paid automatically at the end of Week {state.week+3}, then every four weeks.</p>}
   {!first&&<p>The loan starts repayment in Week {state.week+1}, Day 4. Funding is a loan between separate businesses, not sales income.</p>}
   {first?<div className="market-next"><strong>3. Open, trade, then expand</strong><p>Your remaining {money(Math.max(0,cash-total))} stays in this business’s own account. Enter it, review the included menu or shelf range, then press Start week. Staff and customers begin working on the shared calendar.</p><p>After a week, review the P&L, restock and work toward your next level. To open a second business, lend it surplus cash from this one. The market protects your upcoming bills and operating reserve.</p></div>:<div className="market-next"><strong>Before you expand</strong><p>Finish a trading week and check that your first business can cover its own costs. Buying another building does not raise your player level. All open businesses trade together when you start the next week.</p><p>The new business keeps {money(quote.workingCash)} to operate and must earn enough for wages, stock{method==='lease'?', rent':''} and its {money(Math.ceil(total/term*100)/100)} weekly loan payment. Sales are not guaranteed.</p></div>}
   <p role="status" className="market-notice">{state.notice}</p>
   <button className="mc-button-green market-confirm" disabled={locked||owned||!planning||available<total} onClick={()=>{setPending(id);onChange(s=>acquire(s,id,method==='lease'?'leased':'owned',funding,food?type:undefined,term,{...(businessName.trim()?{name:businessName}:{}),...(built?{design}:{})}));}}>{owned?'Already acquired':locked?`Reach player Level ${quote.level}`:!planning?'Acquire between weeks':available<total?`Need ${money(total-available)} more free cash`:built?'Buy land, build & enter':method==='lease'?'Lease, fit out & enter':'Buy & enter'}</button>
  </article></div>
 </section></div>;
}
